### PR TITLE
ROS: add more documentation and initial tutorial

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by khancyr** [comment]
@peterbarker @rmackay9 Welcome in my hell !

**Comment by khancyr** [comment]
hum I think I  need to put some picture for rqt

**Comment by rmackay9** [comment]
great to see this thanks!

**Comment by khancyr** [comment]
@rmackay9 directly ? Well, I hope I didn't my too much english mistakes ...

**Pull request merged**
