### PR TITLE
Frontend update

### PR DESCRIPTION
**Pull request by khancyr**
Update frontend libs
Remove jQuery and normalize.css as useless and bring some speedup
Correct some small issues

Those leads to a bit faster loading, specially on mobile

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@khancyr Pierre, how can this be tested?

**Review by brunoolivieri — APPROVED** [review]
@khancyr  LGTM (and faster)

@Hwurzburg To test it, you can fetch the PR. Then, you can go to the frontend folder and run a python server locally (python -m http.server).  <tested>

<not tested here> If the integrations do not work, you need to build the wiki to create the JSON files imported from forums(Discourse). With the JSONs you can run a python server and a brownser with CORS disabled (https://alfilatov.com/posts/run-chrome-without-cors/)

**Comment by Hwurzburg** [comment]
if its been reviewed, will merge

**Comment by khancyr** [comment]
I am working on a small script and dockerfile to help review this

**Pull request merged**
