### PR TITLE
common: Change FLOW_ENABLE to FLOW_TYPE

### PR DESCRIPTION
**Pull request by muramura**
I have no variable for FLOW_ENABLE.
I know that setting the device type to FLOW_TYPE disables and enables it.
I change the config parameter name.

### CODE REVIEW

**Comment by rmackay9** [comment]
Thanks very much, merged!

**Comment by brunoolivieri** [comment]
Actually, there are both [FLOW_ENABLE](https://ardupilot.org/copter/docs/parameters.html#foll-enable-follow-enable-disable) and [FLOW_TYPE](https://ardupilot.org/copter/docs/parameters.html#flow-type-optical-flow-sensor-type).

**Comment by rmackay9** [comment]
@brunoolivieri, thanks, I've raised a PR to resolve some of the issues with FLOW_TYPE https://github.com/ArduPilot/ardupilot/pull/13228

**Comment by Hwurzburg** [comment]
when merged there will be a lot of wiki build errors....considerable cleanup....also, as it stands now FLOW_ENABLE going away requires these to be fixed....the links will need to be removed and the params highlighted with ticked boxes...but hopefully we have already gotten the migration notes in for all the parms now in 4.0 not in 3.6

**Comment by brunoolivieri** [comment]
I suggest to wait a week, for the parameters versioning be alive, so I could maintain some references to the 3.6.x and the new links to the 4.x.

**Pull request merged**
