### PR TITLE
Add Holybro RTK M8P gps

### PR DESCRIPTION
**Pull request by Hwurzburg**
@rmackay9 waiting on some new images and review from Holybro before merging this and previous gps PR

### CODE REVIEW

**Comment by vincentpoont2** [comment]
Hi @Hwurzburg, can you please update the spec with this? I have also sent it to your email.
rtk_holybro_h-rtk-m8p_spec_update

**Comment by Hwurzburg** [comment]
Thanjks,Vincent...done...everything else look okay?will merge if so...

**Comment by vincentpoont2** [comment]
> Thanjks,Vincent...done...everything else look okay?will merge if so...

All looks good!

**Comment by Hwurzburg** [comment]
merging

**Pull request merged**
