### PR TITLE
dev: Add ROS 2 page for Gazebo integration

### PR DESCRIPTION
**Pull request by pedro-fuoco**
I plan on adding a quick youtube video showing the gazebo world with a copter in it, it would be nice to have that before merge. 
After this PR I will add a SLAM related page to the wiki.

The technical details have been heavily based on the `ardupilot_gz` README from @srmainwaring, and is linked in the page

### CODE REVIEW

**Comment by Hwurzburg** [comment]
LGTM, can merge now and add video later, or mark it WIP until then...your choice

**Comment by pedro-fuoco** [comment]
@Hwurzburg thanks for the review!
I just added the video, we can merge now

**Comment by Hwurzburg** [comment]
I am going to move the video to the ArduPilot site and update the link and then merge...thanks

**Comment by Hwurzburg** [comment]
@pedro-fuoco  use this video link in the PR...   https://youtu.be/HZKXrSAE-ac

**Comment by Hwurzburg** [comment]
LGTM   thanks

**Pull request merged**
