### PR TITLE
remove dead links

### PR DESCRIPTION
**Pull request by nkruzan**
the 2 i removed have been dead since at least 4/28/2021. the banner pic will need to be updated as well.

### CODE REVIEW

**Comment by darigovresearch** [comment]
Pull request seems to be in order, is there anything else that the maintainers require for this pull request to be merged?

**Comment by Hwurzburg** [comment]
I need to find some time to work on it and remove images and also add a few apps

**Comment by darigovresearch** [comment]
Thanks for letting us know and for taking a look!

May be easier for you to merge this pull request and set up a new issue highlighting what you need to remove and what you need to add if you don't want to leave this pull request open. Someone else from the community may be able to resolve the issues before you can if you set the tags `good first issue` and `help wanted` to encourage them to have a go

**Comment by Hwurzburg** [comment]
archived web apps page...closing

**Pull request closed without merging**
