### PR TITLE
The document of nokov module

### PR DESCRIPTION
**Pull request by 15871812598**
A word error was fixed and 2 pictures were resubmitted because the software version was updated.

### CODE REVIEW

**Comment by 15871812598** [comment]
Old PR:https://github.com/ArduPilot/ardupilot_wiki/pull/4356

**Comment by Hwurzburg** [comment]
We discussed in DEVCALL and our position has not changed:
Since no dev is in a position to answer support questions, this should go into a blog post rather than the wiki. Options at this point are:
1. you can easily amend the original blog post with the updated/changed information yourself, or
2. I can create new blog post or modify the old one, myself....that will take some time for me to work that into my schedule, but am willing to add it to my list

**Comment by 15871812598** [comment]
> We discussed in DEVCALL and our position has not changed: Since no dev is in a position to answer support questions, this should go into a blog post rather than the wiki. Options at this point are:
> 
> 1. you can easily amend the original blog post with the updated/changed information yourself, or
> 2. I can create new blog post or modify the old one, myself....that will take some time for me to work that into my schedule, but am willing to add it to my list

ok,please modify the old one for me.
thanks!

**Comment by Hwurzburg** [comment]
sorry...still on my list to update the blog post...will try to get to it this weekend

**Comment by 15871812598** [comment]
thanks！

**Comment by 15871812598** [comment]
> sorry...still on my list to update the blog post...will try to get to it this weekend

When can you help to update the blog, thanks!

**Comment by Hwurzburg** [comment]
I have updated the discuss posts with the two new images...which are the only changes I see...if I had been told these were the only changes to the discuss post, I could have done them immediately instead of waiting until I had time for reviewing and comparing

**Pull request closed without merging**
