### PR TITLE
Update RPM

### PR DESCRIPTION
**Pull request by Gone4Dirt**
Few commits to update the RPM sensor page:
- Added updates to reflect the new param changes in this PR: https://github.com/ArduPilot/ardupilot/pull/18044
- Added setup of average ESC rpm.  @andyp1per would appriciate it if you could have a quick glance over that to make sure I have added it correctly.
- A few minor corrections and formating.

### CODE REVIEW

**Comment by andyp1per** [comment]
Looks ok to me, although I think this is @yaapu 's code

**Comment by Gone4Dirt** [comment]
Ah, sorry @andyp1per I assumed it was yours.  Should have looked at Git blame.  Thanks for looking at it though.

@yaapu if you could double check the instructions I have done for setting up the ESC telem in the RPM library that would be much appriciated.

**Comment by yaapu** [comment]
@Gone4Dirt  looks good to me too, thanks for documenting the average ESC RPM option

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
Matt, this has a few build errors...there is are no params named RPM1_xxx.....only RPM and RPM2 and RPM3....in addition, I try to avoid using links with RPMx_yy <RPM2_yy>...I'd rather we use something like "in the case of the second RPM instance:" RPM2_MIN<RPM2_MIN> so that the linked param matches the display name they clicked to avoid confusion..ie why did it go there?

**Comment by Gone4Dirt** [comment]
Thanks for taking a look Henry.  Noted about the preferred way to do links.  Will update those.  Regarding RPM1_xxx params.  I have a PR (https://github.com/ArduPilot/ardupilot/pull/18044) which will be changing the RPM_ to RPM1_ hence this pr to the wiki in prep for it going in.

**Comment by Hwurzburg** [comment]
@Gone4Dirt Matt, this will need a rebase since I had to fix build errors in several files caused by the name change....it appears that this is a NFC, as such, when rebased, I can merge rather than waiting for 4.2....because I must fix the build errors when they occur and the param generator is always shows dev, and hence the build errors

**Comment by Hwurzburg** [comment]
closing in lieu of #3771 and #3772

**Pull request closed without merging**
