### PR TITLE
Update JSBSim Instructions

### PR DESCRIPTION
**Pull request by josheeg**
Update JSBSim Instructions to make it more user friendly.

### CODE REVIEW

**Comment by rmackay9** [comment]
I don't know enough about JSBSim to know if this is the correct thing to do or not.  Does anyone else know?

**Comment by auturgy** [comment]
We need to look at this a bit more.  The build instructions work, but just using the -f jsbsim switch on SITL errors out
''' james@auturgy:~/Development/ardupilot/ArduPlane$ sim_vehicle.py -f jsbsim --console --map
SIM_VEHICLE: Start
SIM_VEHICLE: Get JSBSim version
SIM_VEHICLE: "JSBSim" "--version"

=========================================================
You need the latest ArduPilot version of JSBSim installed
and in your \$PATH

Please get it from git://github.com/tridge/jsbsim.git
See
http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html
for more details
=========================================================

SIM_VEHICLE: Killing tasks
james@auturgy:~/Development/ardupilot/ArduPlane$ 
 '''
I think we need to look at SIM_VEHICLE.py, then come back to this.

**Comment by filipsladek** [comment]
I did not notice error you mention but other error if using git://github.com/tridge/jsbsim.git
Solution is in this patch ArduPilot/ardupilot#10185

**Comment by josheeg** [comment]
The link http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html
Does not show the old not working tridge jsbsim.
The newest official jsbsim release works with the Rascal only for me.

**Comment by tridge** [comment]
it should already be clear I think. The Rascal is the default, the MyModel example is for a new model

**Pull request closed without merging**
