### PR TITLE
Update ESC calibration page for DShot and active braking

### PR DESCRIPTION
**Pull request by MichelleRos**
Updates the ESC calibration page to clarify that digital protocols like DShot don't need to be calibrated.
Also the difference between brake on stop and active braking in ESC settings as current settings are unclear as to which is referred to.
Also removed some references to the APMs.

@tridge I've added CAN ESCs in here as well as you suggested, though it seems like this would only apply to integrated CAN ESCs - ESCs that use PWM but via a CAN adapter would still need to be calibrated somehow, right? Not sure if we need to mention this on the page or if it's clear enough?

### CODE REVIEW

**Comment by Hwurzburg** [comment]
LGTM....merging....also will bring that note to top of page rather than at bottom for Plane...and Rover should have a page....on my list

**Comment by MichelleRos** [comment]
Thanks.

**Comment by rmackay9** [comment]
txs for the fix.  It's all fine but "APM" normally refers to hardware.. the old APM board so I think it should normally be replaced with "autopilot" rather than "ArduPilot".

**Comment by Hwurzburg** [comment]
thinks it works either way here... could replace ArduPilot board with autopilot, versus "autopilot board"....but I think its okay as is...

**Comment by MichelleRos** [comment]
@rmackay9 I thought that "autopilot" might confuse users more - in common use an "autopilot" is more the software than the hardware - or both combined (e.g. the Teslas' "autopilot system"). Calling it an "ArduPilot board" makes it clear that we're referring to the hardware board.

**Comment by rmackay9** [comment]
@MichelleRos,

Yeah, not sure about using "ArduPilot board".  Maybe it's all history now but we've had lots of confusion between hardware and software.  APM vs ArduPilot.. Pixhawk vs ArduPilot.  I haven't seen the term "ArduPilot board" much so that seems like a new pair of words and I'm not a fan of using new words when it's not necessary.

For me "autopilot" means hardware.  "board" certainly means hardware so maybe that's an even better choice.

**Comment by MichelleRos** [comment]
@rmackay9 Makes sense to try not to use new terms. Probably "board" is a good one then. I'll remember for future reference. Thanks. 🙂

**Pull request merged**
