### PR TITLE
Added documentation for multi aircraft MAVProxy

### PR DESCRIPTION
**Pull request by mday299**
Poor communication on my part caused https://github.com/ArduPilot/ardupilot_wiki/pull/3850 to be merged prematurely. We don't want these merged before https://github.com/ArduPilot/ardupilot/pull/18973 is in!

### CODE REVIEW

**Comment by Hwurzburg** [comment]
let me know whenever/whatever and I can add for you

**Comment by mday299** [comment]
Thanks for the review @stephendade ! I have incorporated your suggestions.

**Comment by mday299** [comment]
Showed how to get around 0-based indexing with -i the the sim_vehicle call.

**Comment by magicrub** [comment]
https://github.com/ArduPilot/ardupilot/pull/18973 was merged so I'll go ahead and merge this too

**Pull request merged**
