### PR TITLE
Creat log-analysis-tools.rst

### PR DESCRIPTION
**Pull request by artemskorsky**
this page will include log analysis tools

### CODE REVIEW

**Comment by auturgy** [comment]
I’m surprised we didn’t already have this! Thanks.
Can I suggest adding it to common, rather than under copter, and linking to it from http://ardupilot.org/copter/docs/common-logs.html

Regards,

James

**Comment by artemskorsky** [comment]
yes, it will be great,  also we have developed automatic very easy to use geotagging tool, but i dont know where to add, can you suggest? (http://geotag.dron.ee/)

**Comment by rmackay9** [comment]
re the geo-tagging tool, I think the best place is in the [Optional Hardware >> Cameras and Gimbals page](http://ardupilot.org/copter/docs/common-cameras-and-gimbals.html).  I'm planning on re-organising this page at some point to separate out the hardware specific stuff from the more general know-how stuff.

**Comment by artemskorsky** [comment]
Actually when i search "geotagging images ardupilot" it goes to " geotagging images with mission planner)
(http://ardupilot.org/copter/docs/common-geotagging-images-with-mission-planner.html)  I am guessing it would be better to see the alternative geo-tagging tools in the same page

**Comment by artemskorsky** [comment]
> I’m surprised we didn’t already have this! Thanks. Can I suggest adding it to common, rather than under copter, and linking to it from http://ardupilot.org/copter/docs/common-logs.html Regards, James
> […](#)
> On 3 Mar 2019, at 8:50 pm, artemskorsky ***@***.***> wrote: this page will include log analysis tools You can view, comment on, or merge this pull request online at: #1662 Commit Summary Creat log-analysis-tools.rst File Changes A copter/source/docs/log-analysis-tools.rst (1) Patch Links: https://github.com/ArduPilot/ardupilot_wiki/pull/1662.patch https://github.com/ArduPilot/ardupilot_wiki/pull/1662.diff — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Where is the common page you meant above?

**Comment by artemskorsky** [comment]
Hi James, 

what do you mean by " I suggest adding it to common"? can you direct me to this "common page?

**Comment by auturgy** [comment]
Not common page, the “common” set of pages that Sphinx can build into each of the vehicle wikis.
https://github.com/ArduPilot/ardupilot_wiki/tree/master/common/source/docs
It’s not obvious I guess, but where content is useful for more than one vehicle type we generally keep it in there.

**Comment by Hwurzburg** [comment]
@artemskorsky did you move this PR as requested? do not see a new PR in the list...when you do, close this one please....thanks

**Comment by vierfuffzig** [comment]
https://github.com/ArduPilot/ardupilot_wiki/pull/1757

**Comment by rmackay9** [comment]
I think we can close this one now.  If this isn't correct we can certainly restore it.  txs!

**Pull request closed without merging**
