### PR TITLE
Fix dev and common warning

### PR DESCRIPTION
**Pull request by khancyr**
Fix last warning in dev
put file non referenced in exclude patern
add missing image in common
fix some common warning

### CODE REVIEW

**Comment by auturgy** [comment]
LGTM.  Thanks Pierre.

**Comment by khancyr** [comment]
yep. I am just unsure if the exclude patern is the good thing. Normally it should be as those files aren't in any doctree

**Comment by auturgy** [comment]
Yeah.  Those pages are actually linked from http://ardupilot.org/dev/docs/building-the-code.html under "Deprecated instructions".  Adding to the exclude pattern would mean they were no longer built.  I'm not against that, but we should probably discuss it. I'll add a dev call tag.

**Comment by hamishwillee** [comment]
I tend to think that the files should either be removed completely or tagged with an even clearer individual deprecation message. Leaving them in the source is potentially confusing.

**Comment by khancyr** [comment]
I drop the commit with the exclude partern for now to keep only th style fix !

**Comment by hamishwillee** [comment]
@auturgy Then perhaps an even bigger warning up the top of all of these pages. APM2.X is NOT SUPPORTED. These instructions may not work due to deprecated/unavailable toolchain. Use at your own risk.

**Pull request merged**
