### PR TITLE
Add CUAV UAVCAN PM and HV PM

### PR DESCRIPTION
**Pull request by Hwurzburg**
@cuhome since I cannot PR into cuhome repo, I created this separate PR to fix the issues...I was hoping to PR it to them for incorporation into their repo...but cant

- corrected formatting and phrasing
- squashed and rebased
- but still needs batt scale params added for HV PM...if adding in comments below I will fill in and squash again...otherwise its ready to merge
-also, the CAN PMU interface connectors are unclear....XT90? does not appear to have that connection...the V5 cable from FC to PMU is not listed or shown on the CUAV site...what is that power number?5025850670

### CODE REVIEW

**Comment by cuhome** [comment]
@Hwurzburg The connector for can pmu to connect V5 is molex 5025850670; it supports 5v8A.

**Comment by Hwurzburg** [comment]
thanks, do you supply the  PMU to V5 cable?
what are the battery power connectors? it says XT90, but I think that is referring to the battery end of a power cable(s) that you supply with the unit...what is the PMU end?
are the CAN connections JST-GH? do you supply CAN cables with the unit?

**Comment by cuhome** [comment]
@Hwurzburg 
图片

**Comment by cuhome** [comment]
@Hwurzburg 
微信截图_20191120182407

**Comment by Hwurzburg** [comment]
谢谢
thanks for the information....page should be merged shortly
    On Wednesday, November 20, 2019, 05:48:59 AM CST, honele <notifications@github.com> wrote:  
 
 
@Hwurzburg

**Pull request merged**
