### PR TITLE
fix wiki build error

### PR DESCRIPTION
**Pull request by Hwurzburg**
Last plane specific wiki build error fix...now on to the common files used by plane..

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Bruno, citing params without ref is done extensively throughout the wiki....thats how I found out how to highlight them with backticks...since it had to have been already setup before the use in landing, I didnt try to link....but dont mind changing it...

**Comment by brunoolivieri** [comment]
I just would like to set a standard, I meam: or always link the parameters or just give the name of the parameter and the firmware version. 

But I agree with you, there are other pages like that and this PR make this one up to date.

**Comment by Hwurzburg** [comment]
Sorry,in general I think that a good standard,  but  I have to disagree on one point....I think its acceptable to highlight the param if its already been linked in the page.

**Comment by rmackay9** [comment]
I would prefer if we keep the link to the parameter name if possible.  It does allow the user to look at the parameter details for other information including the official description.

**Comment by hamishwillee** [comment]
FWIW there are pros/cons to both linking strategies. Technical authors typically link to first instance of "thing" and then  simply highlight the others - this has advantage for reader that they only see unique links, and know they don't need to click to find out more information.

The main reason I much prefer to link everything is maintenance. It is easy to forget to search for all instances of a linked parameter - but if they are all linked you get the notification of the broken references on  building.

I also tend to not mind going to the same reference twice - it is more irritating for me to be down in the doc, decide I want to see the param, and then have to navigate up the doc to find the link.

Note that when I last did a round of link fixing there were some params that were unlinkable as they are duplicates. I submitted a PR to ensure all are unique, but don't know if that went in.

**Comment by brunoolivieri** [comment]
For further maintenance, to link every parameter looks safer. I also prefer to be able to click on a parameter whenever it appears.

**Comment by Hwurzburg** [comment]
Merging

**Pull request merged**
