### PR TITLE
Wiki: Vicon/MAVProxy. Add documentation on vicon coordinate frame setup

### PR DESCRIPTION
**Pull request by jackhenderson101**
This corresponds to the changes in ArduPilot/MAVProxy#887
Clarifies the correct conventions for coordinate frames for the vicon system and adds some documentation for the Vicon module in Mavproxy.

### CODE REVIEW

**Comment by tridge** [comment]
@jackhenderson101 thanks so much for this!
@Hwurzburg looks good to me, but you may want to check it for style

**Review by Hwurzburg — CHANGES_REQUESTED** [review]

**Comment by Hwurzburg** [comment]
a page for this module should be created in the Mavproxy wiki and added to the index of modules here: https://ardupilot.org/mavproxy/docs/modules/index.html

**Comment by jackhenderson101** [comment]
> a page for this module should be created in the Mavproxy wiki and added to the index of modules here: https://ardupilot.org/mavproxy/docs/modules/index.html

I added a brief explanation of the module options to the mavproxy documentation

**Comment by Hwurzburg** [comment]
Super! thanks! merging

**Pull request merged**
