### PR TITLE
Cygwin Install for new compilers and Eclipse Install update to Python 3.7

### PR DESCRIPTION
**Pull request by hendjoshsr71**
Updates the Eclipse install for Python3.7 to match the install scripts.
Updates the Cygwin install to point to the newest arm-gcc compiler 

Eclipse problem reported on Facebook ArduPilot group

### CODE REVIEW

**Comment by rmackay9** [comment]
Do we need to update the eclipse setup page as well to change 3.6 to 3.7? https://ardupilot.org/dev/docs/building-setup-windows-eclipse.html#building-setup-windows-eclipse

**Comment by hendjoshsr71** [comment]
> Do we need to update the eclipse setup page as well to change 3.6 to 3.7? https://ardupilot.org/dev/docs/building-setup-windows-eclipse.html#building-setup-windows-eclipse

This PR updates that page as well including the relevant picture. Did I miss 3.7 somewhere?
 Though I may need to add a note for common Eclipse issues regarding checking if your cygwin and arm-gcc path variables have been set.

**Comment by Hwurzburg** [comment]
@rmackay9 review requested

**Comment by rmackay9** [comment]
I'm sure this is an improvement so merging.

**Pull request merged**
