### PR TITLE
Create introduction_es.rst

### PR DESCRIPTION
**Pull request by donkrip**
Maybe would be interesting a version of the documentation in Spanish, this is a small contribution to begin.  

Introducción de Copter en español.

### CODE REVIEW

**Comment by hamishwillee** [comment]
@donkrip THanks very much. We don't yet have a multilingual strategy. If we do then we'd probably use the approach outlined here: http://www.sphinx-doc.org/en/stable/intl.html

I need to do some work to get this all set up. Can you check it out and see how you might create and build the translation files for Spanish?

**Comment by OXINARF** [comment]
@hamishwillee Related to this: we should probably consider an online service where people can do translations easily.

**Comment by hamishwillee** [comment]
Yes, we've tried transifex before, and indeed everything else set up to support transifex live service. Problem is that it takes a lot of admin, so I've been considering moving to the approach where we use sphinx translation (native) but have round trip synchronisation with transifex for translation of the files.

**Comment by magicrub** [comment]
if we're working toward a multi-language solution, shall we close this single-page translation PR?

**Comment by rmackay9** [comment]
I guess we should close this because we need to add multi-language support to our wiki first.

**Pull request closed without merging**
