### PR TITLE
Add note re F9P constellation setup

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Review by khancyr — APPROVED** [review]

**Comment by rmackay9** [comment]
txs for this.. it's a bit out of place in some ways because we don't really have notes on specific GPSs on the landing page.  Moving it down below the "U-Blox F9P Firmware Update Procedure" link might be better.. but.. I don't mind too much if this is merged.

**Comment by Hwurzburg** [comment]
I think that it might be missed easily if lower....alternatively, I could add to the F9P gps individually, unfortunately since the mRo device is by reference to their page, it would not be seen for that GPS...I can do it either way...

**Comment by rmackay9** [comment]
I think on the individual F9 pages might be better.. as you say we don't have our own pages for some but where we do have them, that might be best

**Comment by Hwurzburg** [comment]
moved note...merging

**Pull request merged**
