### PR TITLE
Updated the instructions for adding a simulated RPM sensor

### PR DESCRIPTION
**Pull request by CallanDaniel**
Changed RPM_TYPE from 1 to 10 for normal SITL as 1 does not work. Added RPM2_TYPE which needs to be used when running flightaxis link for RealFlight

### CODE REVIEW

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
Actually this is very dependent on the physics model used....some use RPM1, some RPM2, some both....in addition, the wiki needs the  SIM_VIB_MOT_MSK explained as its necessary to get the correct ESC associated with each RPM monitor....so needs some work

**Comment by CallanDaniel** [comment]
@Hwurzburg Copy that - perhaps you could give me a rundown on how this works and I can make a more detailed wiki update? I'm still of the opinion that this is an improvement on the extremely vague info that is currently there regarding RPM simulation.

**Comment by Hwurzburg** [comment]
@CallanDaniel it was just easier to write it up...thanks for bringing this to our attention...

**Comment by CallanDaniel** [comment]
Happy to help! @Hwurzburg

**Pull request merged**
