### PR TITLE
companion-computers.rst: remove LYCHEE

### PR DESCRIPTION
**Pull request by tatsuy**
this topic isn't include on this wiki.

### CODE REVIEW

**Comment by khancyr** [comment]
Hello, 

This is here : http://ardupilot.org/dev/docs/companion-computers.html so it is fine !

**Comment by tatsuy** [comment]
I felt strange that there is an external link on the side menu.
But it's ok. thanks.

**Comment by khancyr** [comment]
yep, but that isn't the only one, so it fine for now. And I really don't  like the raspberry pi page, that isn't maintained ...

**Comment by tatsuy** [comment]
ah, Maverick is too.
I see.

**Pull request closed without merging**
