### PR TITLE
Update Companion-computer.rft

### PR DESCRIPTION
**Pull request by artemskorsky**
I added Lychee Drone computer board  (https://dronee.aero/pages/lychee)

### CODE REVIEW

**Comment by auturgy** [comment]
Could you perhaps expand a little: lychee is a Cube Carrier with a pi cm3, which isn’t clear here.

**Comment by artemskorsky** [comment]
I have extended the name to make it clear to understand

**Comment by artemskorsky** [comment]
Hi,  do i need to change any other thing to get apporeved?

**Comment by khancyr** [comment]
merged thanks !

**Comment by khancyr** [comment]
arf, I should have squash the commits .. sorry

**Pull request merged**
