### PR TITLE
Added instructions to enable Mavlink over UAVCAN

### PR DESCRIPTION
**Pull request by d-v**
Instructions for how to use @magicrub 's Mavlink over UAVCAN PR.

### CODE REVIEW

**Comment by auturgy** [comment]
We should hold off merging this until the functionality is merged into master, I think.

**Comment by Hwurzburg** [comment]
@auturgy, @rmackay9 has this functionality been implemented...can this be merged?

**Comment by hdtechk** [comment]
@Hwurzburg it's still open PR
https://github.com/ArduPilot/ardupilot/pull/8508

**Comment by tridge** [comment]
closing until this feature is in master

**Pull request closed without merging**
