### PR TITLE
Update common-mavlink-mission-command-messages-mav_cmd.rst

### PR DESCRIPTION
**Pull request by TianChang-Yonah**
Errors in 
1) CONDITION_CHANGE_ALT
2) DO_SET_HOME

### CODE REVIEW

**Comment by rmackay9** [comment]
I don't think CHANGE_ALT is supported by any vehicle actually.. not even copter..

**Comment by TianChang-Yonah** [comment]
Alright, so we should hide it or remove from the wiki?

**Comment by rmackay9** [comment]
@TianChang-Yonah, sorry for the slow response, i think we should just remove it..

**Comment by Hwurzburg** [comment]
@TianChang-Yonah, please resolve conflict and make changes...thanks

**Comment by Hwurzburg** [comment]
I edited and merged.....closing

**Pull request closed without merging**
