### PR TITLE
Update common-autopilots.rst

### PR DESCRIPTION
**Pull request by auturgy**
remove Snapdragon Flight.  Board is no longer supported.

### CODE REVIEW

**Comment by rmackay9** [comment]
perhaps we should move the snapdragon page into the archive?

**Comment by rmackay9** [comment]
Yes, instead of completely removing the link we should just move it down a few lines into the "Discontinued boards"

**Comment by auturgy** [comment]
Sure.
We need to check the associated wiki pages too. We stopped supporting this board some time ago.

Regards,

James

**Comment by rmackay9** [comment]
instead of removing it, I've moved the link to the deprecated section.

**Pull request closed without merging**
