### PR TITLE
Add GPIO page as advanced setup

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks pretty good so I've merged it.  I wonder slightly what the difference is between Relays and this GPIO page.  I guess relays are always outputs while GPIO can also be inputs?

As a side note, I wonder if perhaps we should make the "relay" words in this document link to the relay wiki page (or at least the first instance that "relay" appears)

**Comment by Hwurzburg** [comment]
also camera trigger, and perhaps find an input like one of the polarity pins and hot link in that intro list of GPIO uses?

**Comment by rmackay9** [comment]
@Hwurzburg, I'm just wondering though isn't a GPIO a combination of a Relay (which is output and is already documented [here](http://ardupilot.org/copter/docs/common-relay.html)) and a Button which is input?  Maybe we should instead modify this new page to describe how to setup buttons?

**Comment by Hwurzburg** [comment]
I added some links for inputs...but the only button I found was the Rover start button and it has setup on its page...I linked it...

**Pull request merged**
