### PR TITLE
Create a Hardware sub-page for Skyviper to illustrate components

### PR DESCRIPTION
**Pull request by lordneeko**

### CODE REVIEW

**Comment by auturgy** [comment]
Looks good - thanks!
It is probably worth changing the titles in a few places to "SkyViper V2450GPS" rather than "SkyRocket", noting that 3 extra models are coming with ArduPilot this year (or so youtube tells me).

**Comment by lordneeko** [comment]
Yeah I thought about that, but for now I followed the current naming
convention.  But yes, a future PR should focus on refactoring the naming.

**Comment by auturgy** [comment]
OK.  LGTM, but I'll ping @tridge and @peterbarker for this one: I don't generally merge skyviper stuff.

**Comment by peterbarker** [comment]
Merged, thanks!

**Pull request merged**
