### PR TITLE
Remote ID page enhanced. Added products. Corrected grammar

### PR DESCRIPTION
**Pull request by Hwurzburg**
Co-authored-by: Henry Wurzburg <hwurzburg@yahoo.com>

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@optical-o @Bluemarkinnovations  after reviewing #5126 I decided that the best title picture will feature one standalone product from each manufacturer as the best compromise....I also added some verbiage and edited a bit....please comment

**Comment by BluemarkInnovations** [comment]
Fine by me.

**Comment by Hwurzburg** [comment]
need to expand the variations section a bit more....if okay with @optical-o I will then merge it

**Comment by Hwurzburg** [comment]
@optical-o one more chance to review before I merge it

**Comment by optical-o** [comment]
Sorry for the delay. I'm okay with the text. 
However, I fail to see any of our devices in the shared image.

I would appreciate at least one of our devices there.  However, I cannot argue with your choice.

**Comment by Hwurzburg** [comment]
Promiňte....meant to have one in there....send me a clean picture of mini or BS and I will to montage....

**Comment by optical-o** [comment]
We have decided to go with Beacon for the montage.
Thank you 

Dronetag_Beacon

**Comment by Hwurzburg** [comment]
added...merging...thanks!

**Pull request merged**
