### PR TITLE
Revising requirements

### PR DESCRIPTION
**Pull request by lvale**
Revising requirements for TradHeli

### CODE REVIEW

**Comment by rmackay9** [comment]
sure you want to remove the mention of extra long cables?  seems like a reasonable thing to recommend.

**Comment by auturgy** [comment]
Extra long i2c cables just invite problems. Probably good not to recommend them. The gps serial cable is of less concern.
In general, for long cable runs we should be recommending CANBus.

**Comment by rmackay9** [comment]
@ChristopherOlson you're happy with this change?

**Comment by lvale** [comment]
I'll be using the shortest cables I've ever used on MR on a TradHeli. Also if we want to mention long cables we should discuss good practices for such (like using CAT5, etc)

**Comment by ChristopherOlson** [comment]
I would agree with it. Not every heli requires a long cable, especially if the FBL unit tray is on the rear of the heli, where the vast majority now put them. And a person can't buy a proper cable extension (that I could find). Any extension to the I2C wiring must be twisted pair or it will pick up common mode interference, which is going to be a user-made item if a heli requires it. So LGTM.

**Comment by rmackay9** [comment]
txs, Merged!

**Pull request merged**
