### PR TITLE
Copter: add dead-reckoning failsafe explanation

### PR DESCRIPTION
**Pull request by rmackay9**
This adds setup and testing instructions for Copter-4.3's dead reckoning failsafe.  In all honesty, this feature's performance is not as good as hoped but it is included in Copter-4.3 so people should know about it.

This change has been tested on my local machine.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
added to upcoming features

**Comment by rmackay9** [comment]
@Hwurzburg,

OK, moved the link from the Copter failsafe landing page to the upcoming features page.

**Comment by rmackay9** [comment]
@Hwurzburg,

OK, rebased and changed the link to be from the Copter failsafe landing page.

**Comment by rmackay9** [comment]
Great, thanks!

**Pull request merged**
