### PR TITLE
Add Winch page to Copter

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by rmackay9** [comment]
Great, thanks for this.  I've disabled the Winch code by default so users can't actually use it I'm afraid.

I would like to add a page for Winches though in particular the "Daiwa Winch" which is what I used in the Japan Innovation Challenge a few weeks ago.

**Comment by Hwurzburg** [comment]
So should I remove winch control from RCx_OPTIONS and output from SERVOx_FUNCTION?or you re-enabling it?

**Comment by rmackay9** [comment]
@Hwurzburg, i think we should probably remove it from the RCx_OPTIONs and SERVOx_FUNCTIONs parameter values.. thanks for thinking of this.

**Comment by Hwurzburg** [comment]
removed from this PR...fixed the AUX_FUNCTION wiki PR....will do one for SERVO_FUNCTION to remove it

**Comment by Hwurzburg** [comment]
closing since not supported

**Pull request closed without merging**
