### PR TITLE
Update common-benewake-tfmini-lidar.rst

### PR DESCRIPTION
**Pull request by tatsuy**
add the i2c's address description

### CODE REVIEW

**Comment by rmackay9** [comment]
Merged, thanks.  Is it actually necessary to set the _ADDR parameter to make it work?

**Comment by tatsuy** [comment]
Yes, we need to set the _ADDR to use the sensor.

**Comment by rmackay9** [comment]
@tatsuy, OK thanks.  That's not good really, we should default to using the correct I2C address in the driver.  For example I just did this recently for the new LeddarVu8 driver.  Here's an issue on the issues list so we don't forget. https://github.com/ArduPilot/ardupilot/issues/13419

**Comment by tatsuy** [comment]
Do you mean it should use default I2C address if setting RNGFND1_ADDR = 0?
Then, we may need to change the following description.
https://ardupilot.org/copter/docs/parameters-Copter-latest-V4.0.2-dev.html#rngfnd1-addr-bus-address-of-sensor
> A value of 0 disables the sensor.

**Comment by rmackay9** [comment]
@tatsuy, yes, I totally agree with you. There's no need to provide a second way for users to disable the sensor.  Unfortunately this means we will need to go through and see if any of the other drivers are actually allowing the sensor to be disabled by setting the ADDR = 0.

**Comment by tatsuy** [comment]
OK. I understand we will edit the wiki after checking whether the default address is used by setting the ADDR = 0 in the other drivers.

**Pull request merged**
