### PR TITLE
Copter: Add Smart_RTL Documentation

### PR DESCRIPTION
**Pull request by lordneeko**

### CODE REVIEW

**Comment by peterbarker** [comment]
Fixed what James found, squashed and merged!

Thanks!

**Comment by rmackay9** [comment]
Not quite right, the link to the new page is incorrect from the landing page.  It's currently <smart-rtl> but it needs to be <smartrtl-mode>

**Comment by rmackay9** [comment]
I'd like to add it's a well written page..

**Comment by lordneeko** [comment]
I can't take any credit, I just pulled off pages and discussion threads which i found through the discuss server.

So I noticed that on the landing page right away. took me a while to figure out what i'd done wrong.  Added new PR to fix.

**Pull request closed without merging**
