### PR TITLE
Dev: Remove branch instructions, extra fixes

### PR DESCRIPTION
**Pull request by rajat2004**
The [AirSim PR](https://github.com/microsoft/AirSim/pull/2075) has been merged, therefore removing the branch instructions.
Make the requirement of changing the settings more explicit since people miss it

### CODE REVIEW

**Comment by madratman** [comment]
fwiw, you can look at https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing/blob/master/baselines/generate_settings_file.py and generate a settings.json from python and add appropriate fields

**Comment by rajat2004** [comment]
@madratman Thanks for this! Looks very useful, being able to generate the settings directly from a python script could be very useful indeed, will try it out today or tomorrow
However, I feel that the info about this could be added later on in another PR and shouldn't block this one since it removes the instructions to fetch the merged PR branch

**Comment by auturgy** [comment]
Congrats on getting your work merged into Airsim!

**Comment by rajat2004** [comment]
@auturgy Thanks!

**Pull request merged**
