### PR TITLE
Adding Section on USD1 functionality using AP Periph Node. 

### PR DESCRIPTION
**Pull request by SamJCKnox**
I found connecting the USD1 to an autopilot through a CAN Node very challenging as there are many duplicated parameters. I thought it would be useful to others to know how I did it.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Sorry this does not make much sense to me.....why not just connect the SERIAL USD1 to an autopilot serial port?....usually there are spare available

more likely you have an autopilot with a single CAN port....then you could attach a node like this and setup its second CAN port for USD1 protocol and bridge DroneCAN periphs off the DroneCAN port.....setting up a CAN node for that would be worthwhile in my opinion

**Comment by SamJCKnox** [comment]
Fair point, personally, I have run out of serial ports so I need to put the USD1 on CAN.

I think I follow what you are saying in the second part. Are you suggesting a set up like in my figure (attached).

Double CAN Wring Diagram

I wasn’t sure if the Matek CAN node had a second CAN port that could have a second driver as I found this on the matek website:
•	1x CAN, DroneCAN Protocol  (2x GH-4P connectors in parallel)
[Matek L431 CAN Node](http://www.mateksys.com/?portfolio=can-l431#tab-id-2)

For that reason, I assumed I had to use serial.

**Comment by Hwurzburg** [comment]
I think you are right the Matek node does not have two independent CANs....
so this is really a serial port expansion...let me think about the wording to make it clearer and I will push a suggestion...oops, I cant do that since you created the PR off you master instead of a working branch...it would be nice if you could create a working branch and push it as a new PR...

git checkout -b usd1 master

then pushed it as a new PR...that way I could make changes,squash your commits, etc. and push back

**Comment by SamJCKnox** [comment]
I don’t have permission to push a new branch, I get the following error:

**Comment by Hwurzburg** [comment]
@SamJCKnox you did not post the error....in any case we can proceed either of two ways:
1. I am in Austin, TX....if we can arrange a time to chat via Discord, you can share your screen and I can show you how to setup the working branch and push a new PR
2. or I can just take what you have here, close this one, create a PR of my own, make the changes I think needed, and merge it into the wiki
whichever you wish...let me klnow

**Comment by SamJCKnox** [comment]
Sorry, I replied to the GitHub message using email and didn’t realize that images wouldn’t be included.I would be very grateful if you showed me, I do want to contribute more. I am in London, UK, we could do 8pm my time which is 2pm your time? I would be free this coming Sunday, Monday and Tuesday for that time, do any of those suit you?On 16 Jun 2023, at 12:33, Henry Wurzburg ***@***.***> wrote:﻿
@SamJCKnox you did not post the error....in any case we can proceed either of two ways:

I am in Austin, TX....if we can arrange a time to chat via Discord, you can share your screen and I can show you how to setup the working branch and push a new PR
or I can just take what you have here, close this one, create a PR of my own, make the changes I think needed, and merge it into the wiki
whichever you wish...let me klnow

**Comment by Hwurzburg** [comment]
Sure, Sunday my time....get on ArduPilot Discord...https://discord.com/invite/M346dY8... we can voice chat and share screen....search for Henry Wurzburg (henry.wurzburg) and send me a direct message

**Comment by SamJCKnox** [comment]
Great, I will see you then :)On 17 Jun 2023, at 00:54, Henry Wurzburg ***@***.***> wrote:﻿
Sure, Sunday my time....get on ArduPilot Discord...https://discord.com/invite/M346dY8... we can voice chat and share screen....search for Henry Wurzburg (henry.wurzburg) and send me a direct message

**Comment by Hwurzburg** [comment]
@SamJCKnox I was there at the appointed time....did not get a message or your presence on Discord

**Comment by SamJCKnox** [comment]
> @SamJCKnox I was there at the appointed time....did not get a message or your presence on Discord

Hi Henry, I am very sorry I am running late. Are you still free? I have added you on Discord

**Comment by SamJCKnox** [comment]
Thank you Henry for your help. I have corrected my mistake and is now in [PR 5195](https://github.com/ArduPilot/ardupilot_wiki/pull/5195)

**Pull request closed without merging**
