### PR TITLE
common: remove reference to compass calibration stick gestures

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
It might be better to just add a note that this has been removed in 4.1

**Comment by Hwurzburg** [comment]
and is it removed in 4.1? Tridge told me master changes do not go into beta/stable automatically

**Comment by peterbarker** [comment]
On Tue, 24 Aug 2021, Randy Mackay wrote:

> It might be better to just add a note that this has been removed in 4.1

Why?

If we wanted people to know about it *we shouldn't've removed it!* :-)

**Comment by peterbarker** [comment]
Changed this to just add a `.. note::`

**Comment by Hwurzburg** [comment]
rather than ask you to redo and add to futures page, I just did it....thanks closing

**Pull request closed without merging**
