### PR TITLE
partners: There is no drone company Enroute in Japan

### PR DESCRIPTION
**Pull request by muramura**
There is no drone company enroute in Japan.
There is no domain website.
If you are not getting partner support money, you should remove it.

### CODE REVIEW

**Comment by nkruzan** [comment]
translated: https://web.archive.org/web/20211031105334/https://enroute.co.jp/


 June 3, 2021
Enroute Co. , Ltd.

 

Report of company dissolution

 

　Since the establishment of the company in 2006, we have been engaged in business activities centered on the development, manufacture and sale of agricultural and survey drone aircraft as a domestic drone maker. We would like to report that we have resolved to dissolve the company.

　In addition, normal operations will end on June 3, 2021, and liquidation will be completed as soon as the necessary procedures are completed.

　We would like to express our sincere gratitude for the patronage we have received from all of you, and we deeply apologize for any inconvenience caused by the dissolution of the company.

　We would like to inform you in writing, and we pray for the further development of all of you.

 

Inquiries Akasaka Intercity AIR Co. , Ltd.
, 1-8-1, Akasaka, Minato-ku, Tokyo 107-0052 TEL: 03-5571-7788

**Review by rmackay9 — APPROVED** [review]

**Comment by Hwurzburg** [comment]
this creates a massive build error since the row now does not have the same number of columns.....if we had moved to the other method that was proposed, this would be a simple change.....every row below this one must be modified or the last partner moved up to take up the vacancy

**Comment by nkruzan** [comment]
@Hwurzburg does this help? https://github.com/ArduPilot/ardupilot_wiki/compare/master...nkruzan:pr-help/4082  not sure what to do for last row?

**Comment by Hwurzburg** [comment]
@nkruzan, cant seem to get that commit from your repo....if I fetch pr-help/4082 from your repo or that commit from your repo, I get the previous commit (ie master)....so I cant test it either...

**Comment by nkruzan** [comment]
I'm dont have enough git-fu but its here 

https://github.com/nkruzan/ardupilot_wiki/commit/305556d692573687da772533531e0ae60253e744

**Comment by Hwurzburg** [comment]
looks good....push to this PR and will merge...thanks

**Comment by nkruzan** [comment]
I don't have access for that (or don't know how) so I sent @muramura a PR to this branch

**Comment by Hwurzburg** [comment]
I can do that from my machine if he hasn't by tomorrow....Chinese new year and all

**Comment by nkruzan** [comment]
@Hwurzburg I also made a pr #4087 to maybe make this easier to maintain in future

**Comment by Hwurzburg** [comment]
@nkruzan so I pushed the change you made to fix the build error and am merging since @muramura is on vacation for a while

**Comment by nkruzan** [comment]
Thanks!

**Pull request merged**
