### PR TITLE
Fixed the dos line endings under the common sub directory.

### PR DESCRIPTION
**Pull request by grahamjamesaddis**

### CODE REVIEW

**Comment by billbonney** [comment]
What have you fixed these line endings to be? I think unless they obey auto LF/CR rules for git they will get messed up again.

**Comment by billbonney** [comment]
I ran a quick test and it seems this does fix the GitHub editing issue 👍

**Comment by magicrub** [comment]
I'm happy with anything that fixes the crazy whitespace on the commits :)

**Comment by billbonney** [comment]
I check this commit with the?w=1 options and it's only whitespace changes, so will merger https://github.com/ArduPilot/ardupilot_wiki/pull/650/commits/851312fba2bc172c1f3cfdfb3dfcbf051b54cf3d?w=1

**Pull request merged**
