### PR TITLE
Move python packages to requirements.txt

### PR DESCRIPTION
**Pull request by TunaLobster**
DELAY MERGE. There are dependencies that need to be merged before this can go in. See ArduPilot/sphinxcontrib-youtube#4.

This is a change for easier maintenance between the install scripts. Also works as an added bonus to check that the build dependencies are working on the packages ArduPilot maintains.

CI will fail on this PR. I ran this change using my sphinxcontrib-youtube repo and you can see the passing CI change over here.
https://github.com/TunaLobster/ardupilot_wiki/actions/runs/3106686180
https://github.com/TunaLobster/ardupilot_wiki/actions/runs/3106686182

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@TunaLobster is this still something pending or should we close?

**Comment by TunaLobster** [comment]
I think it's still relevant.

**Comment by TunaLobster** [comment]
@peterbarker Does this look good to you?

**Comment by TunaLobster** [comment]
Rebased and moved the python version checks in the bash script to the requiremts.txt file so those now also work on Windows. Checked that it worked on my Ubuntu 24.04 system. I don't have a Windows machine to test this with.

**Comment by TunaLobster** [comment]
Rebased and moved the python version checks in the bash script to the requiremts.txt file so those now also work on Windows. Checked that it worked on my Ubuntu 24.04 system. I don't have a Windows machine to test this with. CI likes it though!

**Review by peterbarker — APPROVED** [review]

**Pull request merged**
