### PR TITLE
Added images

### PR DESCRIPTION
**Pull request by Daddy-Boomalati**
I added the images to my fork and created the pull request. I hope this adds the images...

### CODE REVIEW

**Comment by magicrub** [comment]
these are images for PR https://github.com/ArduPilot/ardupilot_wiki/pull/970 and https://github.com/ArduPilot/ardupilot_wiki/pull/971

**Comment by Daddy-Boomalati** [comment]
I think that this is all I need to finish PR #970 and #971 . I originally tried to "commit" from Github desktop (I'm new...), so that's why I deleted the above images. There should be 11 new images added though.

Thanks,
Dave

**Comment by auturgy** [comment]
G'day Dave,

it'll be a little while until I can build and test this (if someone else 
can make an opportunity, would be awesome), but thanks!

**Comment by OXINARF** [comment]
Yep, it's a bit messy right now so immediate merge can't happen. If I find the time, I'll try to get it right.

By the way, in case anyone is working to fix this, note that the images added in this PR are in the wrong folder, it should be in the `plane/source/images` one. Also, documents in the other PRs need to be changed to reference these images.

**Comment by Daddy-Boomalati** [comment]
No problem!

**Comment by brunoolivieri** [comment]
We may close this PR once it was covered by PR #1938. 

Please reopen it if you disagree.

**Pull request closed without merging**
