### PR TITLE
Add params list to AP_Periph wiki

### PR DESCRIPTION
**Pull request by Hwurzburg**
@peterbarker need params I mentioned to be emitted and captured in AP_Periph-Paramaters.rst file, then will add descriptions to them in this document...

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@magicrub Tom, can you ad the metadata to the gscalar params in AP_Periph/Parameters.ccp that do not have them so that they may be emitted into the WIKI....that is the only thing holding up this merge...thanks

**Comment by magicrub** [comment]
Sure thing. I'll try and get that done this weekend

**Comment by magicrub** [comment]
@Hwurzburg please take a look at https://github.com/ArduPilot/ardupilot/pull/17221

**Comment by Hwurzburg** [comment]
now that its emitting (except for one typo: BUZZ_VOLUME should be BUZZER_VOLUME) will merge

**Pull request merged**
