### PR TITLE
Update setting-up-sitl-on-linux.rst

### PR DESCRIPTION
**Pull request by josheeg**
http://ardupilot.org/dev/docs/setting-up-sitl-on-windows.html
has steps like install git that are not on here that would be needed.

### CODE REVIEW

**Comment by khancyr** [comment]
Those are really old and not accurate information. The setting page is already complet ...

**Comment by khancyr** [comment]
I will add another explicite link to git install, but it is present on http://ardupilot.org/dev/docs/building-the-code.html#building-the-code .
I will check for jbsim dependencies

**Comment by josheeg** [comment]
What pages should a user fallow in what order install on Linux would be
number one.

**Comment by khancyr** [comment]
Hello, I have update instructions for linux.
I will update instruction for jsbsim soon. 

I am closing this

**Pull request closed without merging**
