### PR TITLE
common: remove duplicate link

### PR DESCRIPTION
**Pull request by tatsuy**
unify to "GeoFencing Failsafe"
image

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Unfortunately, Randy wants the Copter/Rover titles to be FENCE FAILSAFES in those sections....
instead, isolate the lower GEOFENCING entry to be plane only

**Comment by Hwurzburg** [comment]
Randy wants them called Fences in Copter/Rover....its a GEOFENCE in plane and shows different info....that link should just be isolated for PLANE site and not removed....

**Comment by tatsuy** [comment]
Thank you for your review.
I changed that GEOFENCE is displayed in plane only.

**Comment by Hwurzburg** [comment]
thanks...merging

**Pull request merged**
