### PR TITLE
update.py: cope with mismatch between build_options.py and features.json

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by TunaLobster** [comment]
I wouldn't be opposed to adding E741 to the .flake8 file.

**Comment by peterbarker** [comment]
> I wouldn't be opposed to adding E741 to the .flake8 file.

Bit of a silly check in this case.  I expect it would help if you were to be assigning the variable into other things, however.

I've made the thing a bit more descriptive.

**Comment by Hwurzburg** [comment]
@peterbarker can I merge this?

**Comment by peterbarker** [comment]
> @peterbarker can I merge this?

I was waiting for you to do so :-)

I've merged it now.

**Pull request merged**
