### PR TITLE
Create pixhawk-camera-trigger-setup page

### PR DESCRIPTION
**Pull request by ovolkmann**
Created page for instructions on triggering the camera directly from Pixhawk (No 3rd Party Hardware). Need help linking images... Image links at bottom of page

### CODE REVIEW

**Comment by magicrub** [comment]
Hi there, thank you for the detailed instructions! In order to remain non-bias on the wiki, would you mind removing the advertising bits? Specifically your Facebook, paypal and blog stuff.

**Comment by magicrub** [comment]
I can edit for you if you prefer

**Comment by ovolkmann** [comment]
Hi Tom, 

 

Please go ahead with the edits and remove the advertising as you see fit. This document was originally put together for our clients and as a help guide for others. Glad that it can be incorporated into the Wiki. 

 

I unfortunately am off on an international drone capacity building trip this week and will not have any time to put towards this wiki post. Are you able to see my images at all? If you feel up to it, please feel free to finalize the documents and get them online. 

 

Kind regards,

 

 

Oliver Volkmann

Operations Manager

 

 

                 

 

MICRO AERIAL PROJECTS L.L.C

     <http://www.microaerialprojects.com/> www.microaerialprojects.com

        Mobile: +1 352 682 0388

 

NOTICE: This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version. Micro Aerial Projects L.L.C., 1625 NW 89th Terrace, Gainesville, Florida 32606 - USA / drone2GIS Inc., 4509 NW 23rd Ave., Gainesville, Florida 32606 - USA.

**Comment by tridge** [comment]
merged

**Pull request closed without merging**
