### PR TITLE
Fix up all links to mavlink.io

### PR DESCRIPTION
**Pull request by hamishwillee**
The mavlink.org links are supposed to be redirected to mavlink.io (currently they are just broken). This fixes the links to point to the correct locations.

### CODE REVIEW

**Comment by auturgy** [comment]
Looks good to me.

**Comment by auturgy** [comment]
I know there has been discussion about where to host mavlink documentation, but this is where it is most actively maintained, so I think it the best option for now.  Thanks @hamishwillee

**Comment by hamishwillee** [comment]
@rmackay9 Can you please merge.

**Comment by hamishwillee** [comment]
Thanks!

**Pull request merged**
