### PR TITLE
Dev: AirSim: Add info about Rangefinder

### PR DESCRIPTION
**Pull request by rajat2004**
Also splits documents into sections
I wanted to have the sections appear in the left bar, but didn't work. Any idea if it's possible?

Can be merged after https://github.com/ArduPilot/ardupilot/pull/15007, https://github.com/microsoft/AirSim/pull/2920

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@rajat2004 does this still need to wait for the airspeed to be added?

**Comment by rajat2004** [comment]
@Hwurzburg This still needs https://github.com/microsoft/AirSim/pull/3364 to be merged, I've pinged the maintainers

**Comment by rajat2004** [comment]
@Hwurzburg This can be merged now

**Comment by Hwurzburg** [comment]
thanks

**Pull request merged**
