### PR TITLE
Add Event38

### PR DESCRIPTION
**Pull request by mwrightE38**
Add Event38 to commercial support page

### CODE REVIEW

**Comment by Hwurzburg** [comment]
can merge after partner coordinator approves this...
"If you or your company wants to be listed here please email partners@ardupilot.org. To be added to this page we request the applicant has made a contribution to ArduPilot or a related project in some way. This includes code, documentation or helping people on the forums. The intention with this policy is to ensure that companies listed here will be active participants in the community."

**Comment by mwrightE38** [comment]
Hey Henry, 

Should already approved. Let me know if you need anything else from me to get this pushed through!

Thanks!

**Comment by auturgy** [comment]
Approved

**Comment by IamPete1** [comment]
@mwrightE38 FYI you might need to mess with your certificate. 

image

**Comment by Hwurzburg** [comment]
@mwrightE38 sorry this has merge conflicts that need to be resolved...if you need help, let me know...

**Comment by tridge** [comment]
I've resolved the conflict and merged

**Comment by mwrightE38** [comment]
Thanks all!

**Pull request closed without merging**
