### PR TITLE
Added SPL telemetry and re-organized telem landing page

### PR DESCRIPTION
**Pull request by Hwurzburg**
addresses #1896

### CODE REVIEW

**Comment by rmackay9** [comment]
Do we want to organise them by range?  It's not bad.. I'm just thinking that there are lots of different criteria that people make their decision on including availability, price, bandwidth...

**Comment by Hwurzburg** [comment]
yeah, but range is really the big decision point IMHO.....kinda matches your TX/RX system capability...

**Comment by Hwurzburg** [comment]
I intend to add DL as a long range telem  system also....there may be others, and we can add them as they are proven....I think Crossfire is working on it, but I hear issues still present...

**Comment by rmackay9** [comment]
Merged!

**Pull request merged**
