### PR TITLE
The document of nokov module

### PR DESCRIPTION
**Pull request by 15871812598**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
are you associated with Nokov? a student? 
Since no ArduPilot Dev is familiar with this system, I think that the best approach would be to create a discuss.ardupilot.org Blog post with this information and in the wiki just add a link to that....that way users can ask questions of someone knowledgeable about this system....also, if you joined the ardupilot discord server and monitored the vision-projects channel.
Is this something you are willing to do?
thanks

**Comment by Hwurzburg** [comment]
I converted to a blog post and linked it in the wiki

**Comment by 15871812598** [comment]
> I converted to a blog post and linked it in the wiki

Why not merged it into master?

**Comment by Hwurzburg** [comment]
It was explained above and also on the MAVProxy PR

**Comment by 15871812598** [comment]
> I converted to a blog post and linked it in the wiki

Hello @Hwurzburg
There is a word error,how do I modify it.
thanks!

**Comment by Hwurzburg** [comment]
@15871812598  just note it on the blog post if its on that, or here if its the wiki link

**Pull request closed without merging**
