### PR TITLE
wiki: fix link

### PR DESCRIPTION
**Pull request by fagoth**

### CODE REVIEW

**Comment by fagoth** [comment]
May be should add a new link to 16.9 version? https://github.com/JazzMaverick/BLHeli/tree/JazzMaverick-patch-1/BLHeli_S%20SiLabs/Hex_files_16.9

**Comment by Hwurzburg** [comment]
thanks

**Comment by fagoth** [comment]
Found on forums that "At the moment, the 16.73 version is the only recommended version that properly supports RPM filtering.", newer versions are very experimental.

**Comment by Hwurzburg** [comment]
okay...merging as is

**Pull request merged**
