### PR TITLE
Common sim: add Gazebo sim + Erle simulations

### PR DESCRIPTION
**Pull request by imuguruza**
Add gazebo simulation and links to tutorials of Erle Robotics

### CODE REVIEW

**Comment by hamishwillee** [comment]
@rmackay9, @magicrub @tridge I am not at all sure about this. It is an update to the "common" Simulation page (which previously just pointed to the dev page on SITL). 

It adds information about ROS/Gazebo but quickly links off-wiki to erle-brain. I don't mind the ROS section at all, but IMO it should probably link to http://ardupilot.org/dev/docs/using-rosgazebo-simulator-with-sitl.html and then that might be updated to link on to Erle brain.

It is also possible that ROS-Gazebo should be at a higher level than just part of SITL story.

Any thoughts?

**Comment by imuguruza** [comment]
Well, I could make a new PR adding content here if you think it makes more sense

**Comment by magicrub** [comment]
HI,

Yeah, ROS has it's own page and the Erle stuff seems a bit too
marketing-ish to be in the Wiki.

**Comment by hamishwillee** [comment]
@imuguruza I'm rejecting this PR as too "marketing ish". We would accept an update to this page which has a sentence about ROS Gazebo and a link to the ROS Gazebo page but not a high level single vendor solution.

As far as I know all ArduPilot/ROS integrations work via SITL and so should be covered in http://ardupilot.org/dev/docs/using-rosgazebo-simulator-with-sitl.html# . I'd be happy for you to add information to that page, but it would have to either integrate properly or clearly identify what you do differently. If you do do something different then perhaps an Erle-Robotics section under a heading "Vendor Implementations" at the end of that article?

**Comment by imuguruza** [comment]
I'll try to make it less commertial, and fit it better to actual content asap

**Comment by hamishwillee** [comment]
@imuguruza Thanks Iñigo  - we really appreciate that!

**Pull request closed without merging**
