### PR TITLE
Update common-ads-b-reciever.rst

### PR DESCRIPTION
**Pull request by cmmcdermott**
I updated this WIKI with newer PING images and added an information video link.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Howdy. Was the intention to display the video inline or link to it? You should be able to display like this 

```
..  youtube:: <stub>
    :width: 100%
```

There is also a missing space near "avionics"

**Comment by hamishwillee** [comment]
@rmackay9 @magicrub This looks good to me, you OK to merge?

**Comment by cmmcdermott** [comment]
Please merge

**Comment by magicrub** [comment]
Can we get the guy on the video to say "ArduPilot.org" instead of "ArduPilot.com"? LOL

**Comment by magicrub** [comment]
@cmmcdermott Craig, do you work at/with uAvionix?

**Comment by magicrub** [comment]
Seems fine, merging. Would be nice if the video was embedded though

**Comment by magicrub** [comment]
I added [this commit](https://github.com/ArduPilot/ardupilot_wiki/commit/dfa1f0d869491611bc7af459048cc69d98a1d763) that changes the youtube url to point to uAvionix's page instead of mid-Atlantic's and embeds the video

**Pull request merged**
