### PR TITLE
Add warning regarding motor interlock for tradheli users

### PR DESCRIPTION
**Pull request by bnsgeyer**
@rmackay9  and @Hwurzburg  I am submitting this PR to address an issue regarding radio failsafe with Copter 3.6 or earlier.  Looking for feedback on the warning placement and clarity.
@JoshWelsh  Any inputs on this PR would be appreciated.

### CODE REVIEW

**Comment by rmackay9** [comment]
looking generally good but it would be nice to put TradHeli right near the start of the warning so that multicopter users only need to glance at it to know that it doesn't apply to them.

**Comment by JoshWelsh** [comment]
Agree with Randy in that it should be as specific as possible about applying only to TradHeli users.  Good call on putting this in there, thanks Bill!

**Comment by rmackay9** [comment]
LGTM!

**Comment by Hwurzburg** [comment]
eveeryone agrees...merging

**Comment by Hwurzburg** [comment]
ack! sorry, I should have tested this first....parameter is wrong....will do a patch later today to fix it...

**Pull request merged**
