### PR TITLE
update GEM1305 and NANO receiver setup guide

### PR DESCRIPTION
**Pull request by datagnss**
- Improve: reduce images size
- Improve: update base and rover mode setup guide
- Fix: need set GPS_TYPE = 5 to let the gps available

### CODE REVIEW

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
fix conflicts...squash to one commit

**Comment by datagnss** [comment]
> fix conflicts...squash to one commit

I tried 😭, but failed to squash it.

**Comment by Hwurzburg** [comment]
I resolved the conflicts, rebased, fixed the param name build error, and squashed....once it passes CI I will merge

**Comment by datagnss** [comment]
> I resolved the conflicts, rebased, fixed the param name build error, and squashed....once it passes CI I will merge

Thanks. @Hwurzburg

**Pull request merged**
