### PR TITLE
Add info on I2C vs UART to Benewake TFmini/Plus

### PR DESCRIPTION
**Pull request by Hwurzburg**
addresses #2045

### CODE REVIEW

**Comment by peterbarker** [comment]
This is correct.

In fact, my device didn't function with the MiniPlus driver on uart... I think that's a known issue, 'though?

**Comment by rmackay9** [comment]
@peterbarker, my guess is that the MiniPlus will work with the UART but you'll need to update the lidar's firmware.  Sadly we don't print out a message saying that the lidar's firmware needs updating.  Instead we just silently fail :-(

**Comment by Hwurzburg** [comment]
I must have miss-understood....I thought @peterbarker said in the issue "I have a uart-version TFMini Plus here, and it is working just fine and dandy on a UART, using the TFMini driver (RNGFND1_TYPE=20 (BenewakeTFmini))." so it did work with the correct driver
In fact, the Sparkfun datasheet and manual for the Plus ONLY mentions UART connections, nothing showing I2C as mentioned on the product brief...but the Benewake site shows a newer version with the I2C interface detailed, so it was either undocumented or a product revision.....
I suggest we use the latest info....and proceed with two drivers one UART and one I2C labeled as such somehow...

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
