### PR TITLE
common: add a list of known UAVCAN/CANbus ESCs

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
We've got a few in the list that aren't strictly UAVCAN ESCs.. so we will have some unhappy users if they go off and buy them thinking they will work.

**Comment by peterbarker** [comment]
@rmackay9 It already says, "CAN ESCs are not yet supported" - is that not sufficient?

There's also the "it works" column :-)

**Comment by rmackay9** [comment]
Merged, thanks!
I combined the "list of known ESCs" into the main uavcan ESC page.

**Comment by pavel-kirienko** [comment]
Sorry for being late, but Zubax Orel 20 are available and are currently being used by some with APM. The link is http://titaneliteinc.com/titanoc/index.php?route=product/product&product_id=995&search=zubax. Right now they are out of stock, but they should be available again soon.

**Comment by peterbarker** [comment]
On Mon, 9 Jan 2017, Pavel Kirienko wrote:

> Sorry for being late, but Zubax Orel 20 are available and are currently
> being used by some with APM. The link ishttp://titaneliteinc.com/titanoc/index.php?route=product/product&product_id

Thanks!  I've updated the document to reflect that these have worked on 
APM.

> =995&search=zubax. Right now they are out of stock, but they should be
> available again soon.

Sadly just about all of these ESCs are stocked in multiple places, all 
"out of stock".  I haven't changed availability, but I'd be happy to link 
to that store (and any other suppliers) once they're in stock!

**Pull request closed without merging**
