### PR TITLE
Fixed broken links in eCalc guide

### PR DESCRIPTION
**Pull request by Daddy-Boomalati**
I'm new to Sphinx, so I'm sorry if this is messy.

Can someone upload the images to GitHub to avoid the broken links in the future? Photo Bucket killed my previous links.

Thanks!

### CODE REVIEW

**Comment by Daddy-Boomalati** [comment]
I would like to have a go at uploading pics, but it won't let me. I get this message:

> Uploads are disabled.
> File uploads require push access to this repository.

**Comment by auturgy** [comment]
ahh - my bad.  Does it give the same error if you try uploading to the same directory in your own branch (https://github.com/Daddy-Boomalati/ardupilot_wiki/tree/master/images), then force-pushing onto this PR?

**Comment by Daddy-Boomalati** [comment]
I have uploaded the images into my fork. How do I perform a push to the Master repository? I like "force-push" better, because it makes me feel like a Jedi ;)

**Comment by OXINARF** [comment]
@Daddy-Boomalati You always need to do changes in your fork, including adding images. Then you do a PR like you did here. So you can just force-push to your _patch-3_ branch and it will update this PR.

**Comment by Hwurzburg** [comment]
#2004 merged, closing this PR

**Pull request closed without merging**
