### PR TITLE
common-wiki-editing guide: Restructure to put Infrastructure details …

### PR DESCRIPTION
**Pull request by lordneeko**
…at the top.

I felt like each time I looked at this page, that the infrastructure section should be the intro to the section.  So I suggest pulling it to the top.

### CODE REVIEW

**Comment by lordneeko** [comment]
Just for my opinion (if it matters :-D )
When I look at the wiki editing guide, the first thing I want to know if the language I'm writing in and how it is structured, and built. Also, I want to know how I can setup my environment to do it.

That's all covered in the infrastructure paragraph.  Once I know the language, structure, and have my environment ready, then, I can get into, how to make a code change.

Just my 2-cents.

**Comment by khancyr** [comment]
it makes sense, so why not !

**Comment by rmackay9** [comment]
looks OK to me as well so merging!

**Comment by hamishwillee** [comment]
@rmackay9 All, I would revert this - I absolutely hate it. The old structure made sense
- Welcome to community
- Quick edit
....
- How it all works, that you don't really need to know.

Now you have
- All the stuff you don't really need to know
- This welcome to community that no longer makes any sense at the end of a section about infrastructure.

> All members of the community are welcome to join and contribute to this
 wiki! Any help you can offer is appreciated — from creating new articles	 wiki! Any help you can offer is appreciated — from creating new articles
 and re-validating older articles, through to fixing broken links and	 and re-validating older articles, through to fixing broken links and

Blah blah.

Horrible.

**Comment by lordneeko** [comment]
I think that's a little harsh. As a technical writer you should know better. A well written explanation of the system and how it works is always the opening volley of a technical guide, at least for any software programmer's manual I've ever seen or contributed to.

I agree, however, that the paragraphs you mentioned should be moved back to the top.

> All members of the community are welcome to join and contribute to this wiki! Any help you can offer is appreciated — from creating new articles and re-validating older articles, through to fixing broken links and spelling/grammatical errors.
> 
> We’ve made that very easy - all you need for access is a Github account.
> 
> This provides everything you need to help the wiki grow!

**Comment by lordneeko** [comment]
I first started thinking about changing it after the third time I tried to remind myself what rst stood for...because it's not REST, and then being reminding for the third time that it was half-way down the page between one section on how to edit the wiki, and another section on how to edit the wiki.

**Comment by hamishwillee** [comment]
@lordneeko Fair call. As a member of a community I should know better. I apologise for being so direct. In particular unwarranted because you have made so many other contributions that can't be faulted.

As a technical writer I stand by the assessment of the change. There are many ways to structure documents. I hold with the rule that you should make people read as little as possible. As most people can work through the github UI, they need to know very little about the infrastructure. Forcing them to read this stuff for the easy changes seems to me to be asking for trouble. 

In addition, for any content that might be translated, it is best to avoid significant structural changes unless you're pretty sure of them. That may not be a concern here.

Moving that text to the top will be better. If you choose to keep this structure you probably also modify the text "Most of this information is provided for interest only ...", since my first question would be why are you providing this for interest only information first.

I hope I have convinced you. But if not, it is not the end of the world. Just suboptimal.

**Comment by hamishwillee** [comment]
> I first started thinking about changing it after the third time I tried to remind myself what rst stood for...because it's not REST, and then being reminding for the third time that it was half-way down the page between one section on how to edit the wiki, and another section on how to edit the wiki.

That's a valid point, that could be fixed without changing the structure.

**Pull request merged**
