### PR TITLE
Dev: Fix DroneKit URL

### PR DESCRIPTION
**Pull request by brunoolivieri**
Fixing Dronekit URL

### CODE REVIEW

**Comment by auturgy** [comment]
Please check with @CraigElder before merging this one.

**Comment by auturgy** [comment]
Sure: the new URL does have a clone of the docs, it’s just that they’re “unofficial” and I don’t want linking to them to have unintended consequences for Craig. I think it should be fine, but I’d like him to ok this.

Regards,

James

**Comment by rmackay9** [comment]
@CraigElder, any thoughts on this one?  You're OK with the new link or is there another?

**Comment by rmackay9** [comment]
I've gone ahead and merged this because it's a better link but hopefully Craig can respond as well and if necessary we can change the link

**Pull request merged**
