### PR TITLE
Soaring/Aux function: Update for new soaring aux function.

### PR DESCRIPTION
**Pull request by samuelctabor**
Update documentation for when https://github.com/ArduPilot/ardupilot/pull/14815 is merged.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
thanks Samuel for this....we will have to change the option number when time comes, no doubt

**Comment by samuelctabor** [comment]
I've updated the index to the final one and rebased.

**Comment by Hwurzburg** [comment]
Added to upcoming features page..so docs are available to those using Master..this will merge when in a release...

**Comment by samuelctabor** [comment]
Superceded by #3013

**Pull request closed without merging**
