### PR TITLE
Add MAVProxy to wiki

### PR DESCRIPTION
**Pull request by stephendade**
This is a rather _large_ set of changes for #2731.

I've taken the documentation over at http://ardupilot.github.io/MAVProxy/html/index.html and done some fiddling (structure, heading, format templates) to align with the wiki layout.

Only outstanding issue is I;m not sure how to include mavproxy in the dropdown menu:
Screenshot from 2020-05-19 14-23-41

### CODE REVIEW

**Comment by Hwurzburg** [comment]
look at the TOC at the bottom of ardupilot site index :https://github.com/ArduPilot/ardupilot_wiki/blob/master/ardupilot/source/index.rst

also update.py must be changed to build this...add to ALLWIKIS I think

**Comment by brunoolivieri** [comment]
Hi there,

I guess you should edit the Wiki theme at https://github.com/ArduPilot/sphinx_rtd_theme . The top menu is described in the file. https://github.com/ArduPilot/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/z_top_menu.html

To test that, you could uninstall the theme in your box and install your forked menu.

**Comment by stephendade** [comment]
>look at the TOC at the bottom of ardupilot site index :https://github.com/ArduPilot/ardupilot_wiki/blob/master/ardupilot/source/index.rst

Done

>also update.py must be changed to build this...add to ALLWIKIS I think

Done

**Comment by stephendade** [comment]
>I guess you should edit the Wiki theme at https://github.com/ArduPilot/sphinx_rtd_theme . The top menu is described in the file. https://github.com/ArduPilot/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/z_top_menu.html

Ahh, that's where it is! Done in https://github.com/ArduPilot/sphinx_rtd_theme/pull/14

**Comment by Hwurzburg** [comment]
built and fixed one small error...squashed...will add to theme next...also I have asked @brunoolivieri , Bruno, how we get the site added to an inventory file so that cross link to this site work from other sites...

**Comment by Hwurzburg** [comment]
merging

**Pull request merged**
