### PR TITLE
Fix case error with log messages

### PR DESCRIPTION
**Pull request by stephendade**
The log message page had the wrong case (logmessages.rst vs LogMessages.rst).

This PR restores it back to all lower-case

### CODE REVIEW

**Comment by peterbarker** [comment]
Merged, thanks!

**Comment by Hwurzburg** [comment]
and this just re-breaks everything I had just fixed over the last week

**Comment by Hwurzburg** [comment]
I reverted this so I can continue working without massive errors until I understand this.....there are other impacts

**Comment by Hwurzburg** [comment]
okay, I have had time to track the issue:
- originally the file was lowercase
- in Dec Stephen changed to CamelCase which created massive build errors
- I fixed those build errors in the wiki and in gitignore last week....which also required removing the old lowercase files from local source since they were no longer being autoremoved
- this change recreates all the build errors for CamelCase files which needed to be purged locally after this fix and does not fix the gitignore
- I will re-re-revert and fix the gitignore
- perhaps next time I will get a chance to review wiki changes before merging, even if its not my area of expertise (update.py) so I can test build locally

**Pull request merged**
