### PR TITLE
"ans" -> "and"

### PR DESCRIPTION
**Pull request by arikrupnik**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
rebased to get rid of repeated already merged older commit, squashed to get rid of merge comment....merging...thanks

**Comment by arikrupnik** [comment]
Thank you for taking them. If the policy is to rebase, I'm happy to do that going forward.

**Comment by Hwurzburg** [comment]
not sure if the superfluous merge commit message would have made it into the history, but I didnt chance it....we are not as strict on wiki about squashing commits, but I try to do it so that the history is more readable and searchable...

the preferred (but not required) flow is: sync up your local master to AP wiki master, branch off it for the changes, squash them into a single commit if related (make separate commits or preferably, branches with separate pushes, if not), push branch to your local, PR to master repo....

I did not squash the two typo commits into one(just rebased to get rid of old merged commit and merge message), but usually would have..since they were on the same subject...

**Comment by arikrupnik** [comment]
Thank you, Henry. I try to follow local rules in repositories to which I contribute.

Ari.

**Comment by Hwurzburg** [comment]
your contributions are much appreciated!

**Comment by arikrupnik** [comment]
Thank you for saying that.

Have you had enough rest to tackle the possessive PR? :=)

**Comment by Hwurzburg** [comment]
tomorrow I should not be in any rush on anything....and can take my time

**Pull request merged**
