### PR TITLE
fix: Removes full stop in ardupilot conf

### PR DESCRIPTION
**Pull request by darigovresearch**
Should resolve https://github.com/ArduPilot/ardupilot_wiki/issues/3553 if merged

### CODE REVIEW

**Comment by Hwurzburg** [comment]
this needs conflicts fixed now...

**Comment by darigovresearch** [comment]
@Hwurzburg I have now adjusted it to match the current year from the other merged pull request

**Comment by darigovresearch** [comment]
@Hwurzburg is there anything else that is required for this pull request to be merged?

**Comment by Hwurzburg** [comment]
> @Hwurzburg is there anything else that is required for this pull request to be merged?

still has rebase conflicts....will try to fix later today

**Comment by Hwurzburg** [comment]
have fixed the rebase conflicts...merging..thanks

**Comment by darigovresearch** [comment]
Thanks for taking a look, would have been able to resolve this ourselves but don't have write access to the repository

**Comment by Hwurzburg** [comment]
did not require that...just needed a rebase and conflicts fixed, then re-pushing to your repo branch....

**Pull request merged**
