### PR TITLE
ROS: update rosdep command

### PR DESCRIPTION
**Pull request by srmainwaring**
Add `-y -r` flags to continue on error and accept all changes.

### CODE REVIEW

**Comment by Ryanf55** [comment]
Which package do we need the `-r` flag for?

**Comment by srmainwaring** [comment]
Gazebo harmonic packages are not found using `rosdep` on jammy. Could use skip keys or the alternative rosdep sources for non-standard distros as is done in the ardupilot_ros CI workflow definition.

rosdep-missing

**Comment by Ryanf55** [comment]
Yea, perhaps it's time we start recommending this workflow to our users. It works well.
https://github.com/ArduPilot/ardupilot_ros/blob/940efb9a41d80eb6d4ae5a0f66cdab412f2a1e70/.github/workflows/colcon.yml#L44

**Comment by Hwurzburg** [comment]
going to merge as is, since it appears okay...further changes can be in a future PR

**Pull request merged**
