### PR TITLE
Remove/Archive ERLE references 

### PR DESCRIPTION
**Pull request by Hwurzburg**
addresses #2081

### CODE REVIEW

**Comment by khancyr** [comment]
Hello,

I am pretty sure Navio2 isn't discontinued yet and still supported by Emlid

**Comment by Hwurzburg** [comment]
You are correct...got on a roll...will fix

**Comment by proficnc** [comment]
Please keep the PXF stuff, we are considering a new run of these boards now that the new BB is out. 

PXF is a ProfiCNC product that was built under license by ERLE

**Comment by Hwurzburg** [comment]
@khancyr fixed Navio2 mistake....sorry...

@proficnc  No PXFmini stuff is removed (or will be...at most the links on a few remaining pages will be removed and moved to the archive list), currently the PXFmini is listed as a discontinued board...this PR only adds the archived label to two docs, but does not actually remove the only two links from  vehicle assembly pages to the PXFmini (which actually should be removed and moved to the archived documents list at some point since the product is not available, nor has concrete plans for availability)....in any case, if the PXFmini becomes available again, it can be quickly and easily re-highlited as an available device on the flight controllers and assembly pages, or pages even modified if changes to the product are made...we want to make sure that any available ArduPilot compatible product is promoted and highlited...
no documents are removed, only links relocated for inactive pages...

**Pull request merged**
