### PR TITLE
removed references to old firmware revs

### PR DESCRIPTION
**Pull request by Hwurzburg**
focusing on Plane now

### CODE REVIEW

**Comment by brunoolivieri** [comment]
I do understand that makes the text easier to maintain and read. However, the old versions will be still available those versions on the firmware? Maybe it would be a good idea to set the floor version as a modern version as v4.x.x.

**Comment by Hwurzburg** [comment]
> I do understand that makes the text easier to maintain and read. However, the old versions will be still available those versions on the firmware? Maybe it would be a good idea to set the floor version as a modern version as v4.x.x.

ALL versions of older released firmware are available (via MP)....but we decided last year to only carry warnings on when new features/operations occur for the last two firmware stable revs.. and I am archiving any significant info blocks for older firmware ..otherwise clutter accumulates and makes reading difficult...

**Review by rmackay9 — APPROVED** [review]
LGTM at least for the non-plane pages

**Review by tridge — APPROVED** [review]

**Comment by tridge** [comment]
good idea, thanks Henry!

**Pull request merged**
