### PR TITLE
add setup videos for trad heli

### PR DESCRIPTION
**Pull request by bnsgeyer**
This PR adds setup videos for 
Swashplate setup and leveling
Collective and stabilize curve setup
Flight controller mounting 
Flight controller connections and transmitter setup. 

@Hwurzburg please upload the videos [here](https://drive.google.com/drive/folders/1fNPRdNuvSaJQGEBA5j3mnc4NpRWkN9QY)  to YouTube.  There are 4 videos. I only see three at the moment. I will get the other one up there when I get home. 
Once they are uploaded, I will update the PR with the YouTube links.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
will do once back from vacation next week...should make a playlist for trad heli on the ardu youtube site also...

**Comment by bnsgeyer** [comment]
I have all of the videos at the link provided in my original post.  So ready when you are.

**Comment by Hwurzburg** [comment]
Radio setup https://youtu.be/JagHOc0_mNQ
Swashplate Leveling https://youtu.be/oA-9FFYC6Ek
Collective Curves https://youtu.be/qfOuZc_7J4g
Autopilot Placement https://youtu.be/sJEO4CUhwjs

They are part of the Heli setup playlist, that should have the older ones removed...let me know and I can remove them and also can change order of the new ones if you wish...  https://www.youtube.com/playlist?list=PLC8WVaJJhN4wBxjH1IGJNTRK6dGJrvh4y

**Comment by bnsgeyer** [comment]
@Hwurzburg Of that 4 part series, I think you can remove the first to setup videos.  My videos aren't a 1 for 1 replacement but I think those videos are pretty outdated.  Parts 3 and 4 are outdated but I don't have a video to replace them.  The concepts are the same except some of the units have changed an the parameters like decapercent to percent.  I will try to replicate those videos with newer ones that discuss each type of Rotor speed control setup separately so users can just watch the one they wish to use.  I will make the changes to the PR and let you know when I am ready to merge.
Thanks!   

So the order of the new videos should be 
Autopilot placement
Radio setup
Swashplate Leveling
Collective curves
old video part 3
old video part 4

**Comment by bnsgeyer** [comment]
@Hwurzburg  I added the youtube links and modified the ground school page to reflect the new videos but left the 3rd and 4th video from the original set because I don't have videos to cover that yet.  I think this is ready for merging

**Comment by Hwurzburg** [comment]
done
    On Saturday, October 8, 2022 at 08:50:16 AM CDT, Bill Geyer ***@***.***> wrote:  
 
 


@Hwurzburg Of that 4 part series, I think you can remove the first to setup videos. My videos aren't a 1 for 1 replacement but I think those videos are pretty outdated. Parts 3 and 4 are outdated but I don't have a video to replace them. The concepts are the same except some of the units have changed an the parameters like decapercent to percent. I will try to replicate those videos with newer ones that discuss each type of Rotor speed control setup separately so users can just watch the one they wish to use. I will make the changes to the PR and let you know when I am ready to merge.
Thanks!

So the order of the new videos should be
Autopilot placement
Radio setup
Swashplate Leveling
Collective curves
old video part 3
old video part 4

**Comment by Hwurzburg** [comment]
very strange, 3 hours ago I was asleep!!??? wonder how the last comment was added to this PR?

**Pull request merged**
