### PR TITLE
Soaring: Clarify supported boards.

### PR DESCRIPTION
**Pull request by samuelctabor**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
rather than a link to the discus topic, use common-limited-firmware  ref...it list what not in any board build

**Comment by samuelctabor** [comment]
Thanks, should be fixed now.

**Comment by samuelctabor** [comment]
Hi Henry, No problem, I've removed it.

**Comment by Hwurzburg** [comment]
thanks....merged

**Pull request merged**
