### PR TITLE
Add virtual flybar to ACRO mode

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by bnsgeyer** [comment]
@ChristopherOlson can you review this wiki PR  too?

**Comment by ChristopherOlson** [comment]
@bnsgeyer I do not know about the formatting part for the wiki, but the content looks fine to me. It is a very simple mode to set and I know of no one that has had problems with setting it to their liking. So I think the simple description is very good.

**Comment by bnsgeyer** [comment]
@ChristopherOlson I wasn't worried about the format.  Henry has got that pegged.  I just wanted you to look at it to make sure we didn't miss anything.   Thanks!

**Comment by bnsgeyer** [comment]
@Hwurzburg I think it just needs a sentence that says that it can only be used with the trainer mode disabled.  Otherwise I think it looks great!

**Comment by Hwurzburg** [comment]
something different than line #83?

**Comment by ChristopherOlson** [comment]
@Hwurzburg I think Bill just missed that. It looks very good to me.

**Comment by Hwurzburg** [comment]
okay merging....thanks!

**Comment by bnsgeyer** [comment]
@hwurzburg sorry. I missed the note. However I do feel the note should be moved up to just under the paragraph (1st paragraph) where it tells the user how to invoke this feature.

**Pull request merged**
