### PR TITLE
Update intel-edison.rst

### PR DESCRIPTION
**Pull request by auturgy**
fixed post-flash.sh to post-install.sh and wifi credentials path

### CODE REVIEW

**Comment by magicrub** [comment]
@jmachuca

**Comment by magicrub** [comment]
@jmachuca77

**Comment by jmachuca77** [comment]
post-install.sh is a different script written by intel, I am not sure what that will do. If you cannot access post-flash.sh, there might be a problem with the path. the file should be in ~/.local/bin. Wifi credentials path is fixed on pr #622

**Comment by auturgy** [comment]
image

**Comment by magicrub** [comment]
Do you suggest we close this?

**Comment by auturgy** [comment]
Probably.  I'll re-flash the edison and walk through the wiki again, then raise a new PR if necessary

**Comment by auturgy** [comment]
PR closed.  I'll re-flash the edison and walk through the wiki again, then raise a new PR if necessary.

**Pull request closed without merging**
