### PR TITLE
Combine schools and training into one page

### PR DESCRIPTION
**Pull request by Hwurzburg**
addresses issue #1704

### CODE REVIEW

**Comment by rmackay9** [comment]
So we just need to be sure that ardupilot.org's About >> Schools link continues to work (i.e. maybe it needs to be redirected or removed)

**Comment by Hwurzburg** [comment]
where do all these banner menus reside?

**Comment by rmackay9** [comment]
@Hwurzburg, I don't know but @OlivierJB should know I think.

**Comment by OlivierJB** [comment]
Those menus are on ardupilot.org within the concrete5 framework.

The About/schools link to Ardupilot,org currently points to http://ardupilot.org/dev/docs/schools.html, I could change that to the new link, looks like http://ardupilot.org/dev/docs/commong-training-centers.html ?

**Comment by Hwurzburg** [comment]
I think we need to have a call specifically to discuss the entire approach to top banners/ duplications/ links into specific wiki sites, etc.
I will ask on the dev skype when Olivier,Tridge,Randy and myself could get together...

**Comment by Hwurzburg** [comment]
@OlivierJB so at this point, I think changing the main page banner menu ABOUT/Schools to point to this new page is what we should do....when that is done, I will merge this update...and remove the old page...thanks

**Comment by OlivierJB** [comment]
Henry, sounds good. Let's try to coordinate, I'll try to catch you on mumble.

**Comment by Hwurzburg** [comment]
WIKI call tonight at 2300UTC?

**Comment by OlivierJB** [comment]
That'll work for me. See you there.

**Comment by Hwurzburg** [comment]
thank @OlivierJB Merged

**Pull request merged**
