### PR TITLE
dev: add gflags_catkin ros package for ROS/Gazebo Simulator page

### PR DESCRIPTION
**Pull request by glody**

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @alexbuyval 

Would you be able to comment this change (and linked issue #439) make sense? I haven't tried it, but it sounds pretty reasonable :-)

**Comment by hamishwillee** [comment]
@rmackay9 I don't have time to test this. Assigning to you. Feel free to handball :-)

**Comment by magicrub** [comment]
What's the status of this? should we close this in favor of PR #480 ?

**Comment by hamishwillee** [comment]
Yes. The [typo should be re-fixed](https://github.com/ArduPilot/ardupilot_wiki/pull/438/files?w=1) in the introduction through.

**Pull request closed without merging**
