### PR TITLE
Fix grammar issue in "Choosing a flight controller"

### PR DESCRIPTION
**Pull request by aaaaaaudrey**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Congrats on first submission! the equal sign underline must be extended under longer title...

**Comment by aaaaaaudrey** [comment]
Fixed. Oops.

**Comment by Hwurzburg** [comment]
thanks...since its only two commits, I wont "squash" them before merging...

**Comment by Hwurzburg** [comment]
merged...thanks!

**Pull request merged**
