### PR TITLE
Update git-submodules.rst

### PR DESCRIPTION
**Pull request by auturgy**
removed inaccurate information.  Needs a follow on to add the sync script etc

### CODE REVIEW

**Comment by Hwurzburg** [comment]
LGTM...thanks

**Comment by Hwurzburg** [comment]
James, next time please do the work on your own local branch rather directly on the repo...thanks

**Comment by auturgy** [comment]
that was on a branch, just through the browser.  Did it create the branch off the repo?

**Comment by Hwurzburg** [comment]
if you look at the top of this PR its a request to commit into wiki master from wiki:Submodules-minor-update instead of from your forked repo of the wiki, which is where PR requests should be created, just like for the ArduPilot code wiki

**Pull request merged**
