### PR TITLE
Update common-pixracer-overview.rst

### PR DESCRIPTION
**Pull request by ardubird**

### CODE REVIEW

**Comment by rmackay9** [comment]
For this one we definitely need to add mRobotics because they are the inventor of it actually (the original company merged with mRobotics about a year ago).
https://store.mrobotics.io/category-s/112.htm

**Comment by auturgy** [comment]
Suggest not only including mRo, but checking with Jordi and PhilK before merging.

**Comment by lvale** [comment]
Last I heard those vendors didn't have reliable PixRacer boards.

**Comment by lthall** [comment]
Yeh, to the best of my knowledge the pixracer boards that were sold in hobbyking were of an early firmware revision and will not run using master.

Putting BangGood on as a source is never a good idea as they sell a lot fake components.

Close it I say!!

**Comment by auturgy** [comment]
ping @j07rdi

**Comment by j07rdi** [comment]
Also pinging @pkocmoud so we can discuss it. Thanks for the consideration.

**Comment by pkocmoud** [comment]
Thanks - Looks fine to me.

**Comment by rmackay9** [comment]
I'm pretty sure the hobbyking and banggood links at the end won't work because they're missing the final double underline (__)

**Comment by auturgy** [comment]
thanks @ardubird - merging.

**Pull request merged**
