### PR TITLE
Add github actions test

### PR DESCRIPTION
**Pull request by khancyr**

### CODE REVIEW

**Comment by brunoolivieri** [comment]
Hi there!

Would this intend to check a PR before a merge as CI does? IFF yes, I highly suggest use the build command "python update.py --clean --paramversioning --parallel 4 --enablebackups" as it runs on the server.

**Comment by davidbuzz** [comment]
lgtm

**Comment by tridge** [comment]
needs to also run the github actions

**Comment by Hwurzburg** [comment]
@khancyr can you address Tridge's comment?

**Comment by khancyr** [comment]
@brunoolivieri I don't think we want the `clean` flag, as it set to use master banch. 
`paramversioning`, need more complex build as it need to generate all the parameter. I will open an issue an do it later
`enablebackups` : what the use for this one ? just testing that we can do backup ?

@Hwurzburg nope, I don't have enough priviledge on wiki to enable actions. The action result could still be seen on my fork : https://github.com/khancyr/ardupilot_wiki/actions/runs/395823375

**Pull request merged**
