### PR TITLE
Add Holybro RTK F9P family gps

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by rmackay9** [comment]
Ah, great that another F9P GPS is available..

**Review by rmackay9 — APPROVED** [review]

**Comment by vincentpoont2** [comment]
Hi @Hwurzburg, can you please update the spec with this? I have also sent it to your email.
rtk_holybro_h-rtk-f9p_spec_update

**Comment by Hwurzburg** [comment]
Thanks Vincent...done...will merge if it looks okay...

**Comment by Hwurzburg** [comment]
merging

**Pull request merged**
