### PR TITLE
common: add SBus serial servo output docs

### PR DESCRIPTION
**Pull request by kd0aij**

### CODE REVIEW

**Comment by auturgy** [comment]
Ref: https://github.com/ArduPilot/ardupilot_wiki/issues/279

**Comment by kd0aij** [comment]
@auturgy I didn't realize that the PX4IO SBus output was not documented. I've never tested the PX4IO SBusOut pin myself; does it actually work?

**Comment by auturgy** [comment]
It does, although I’m not sure how many use it.
I think merging what you’ve done first is fine, and a good reminder for me to finish off documentation for the other method.
As with your implementation, you can’t set refresh rate by channel/group, and it’s not bidirectional.

**Comment by kd0aij** [comment]
It would be nice to coordinate the servo output docs to make it clear that the PX4IO is a separate module which is only present in the "Pixhawk" flight controllers. There's also some potential confusion between "MAIN" and "AUX" outputs since those terms are used to differentiate between the IO and FMU PWM outputs of Pixhawk1/2 and some FCs have only the FMU, hence no "MAIN" outputs.

**Comment by kd0aij** [comment]
@lvale Here's the first bit of SBusOut documentation. Comments and suggestions appreciated.

**Comment by lvale** [comment]
@kd0aij I would only add on the title the reference to Serial, as to not confuse with the "traditional" SBus output of the full sized PixHawks :)

**Pull request merged**
