### PR TITLE
Add Holybro Pixhawk 6X Pro to common-autopilots.rst

### PR DESCRIPTION
**Pull request by vincentpoont2**
Add Holybro Pixhawk 6X Pro

### CODE REVIEW

**Comment by vincentpoont2** [comment]
@Hwurzburg Can I add the product link here first?

**Comment by Hwurzburg** [comment]
Yes...needs to be called "pro" in label...also does this use the existing 6X firmware?

**Review by Hwurzburg — CHANGES_REQUESTED** [review]

**Comment by vincentpoont2** [comment]
> Yes...needs to be called "pro" in label...also does this use the existing 6X firmware?

Thanks, forgot the "Pro" part. It does use the same target as the Pixhawk 6X.
I put the note here: https://docs.holybro.com/autopilot/pixhawk-6x-pro/supported-firmware

**Comment by Hwurzburg** [comment]
shouldnt we update this page instead?I can add this link in the interim

**Pull request merged**
