### PR TITLE
fix wiki build errors: TOC issues

### PR DESCRIPTION
**Pull request by Hwurzburg**
no content change...this fixes almost all TOC errors (assuming previous PRs are merged)....the "common-partners-program" document does not fit into any TOC tree that I can find...its just a link from the "common-partners' page....suggestions on what to do with it to eliminate the error are welcomed...

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks pretty good but are you sure we should delete the pixhackv5 board's page?

**Comment by Hwurzburg** [comment]
the board appears to be the predecessor to the CUAV V5 Plus.....it is not referenced by any other document or TOC tree....if its never linked...its never seen...and generates a TOC error

**Comment by auturgy** [comment]
I’ll update the supported autopilots page and stick a reference in to it.

Regards,

James

**Comment by Hwurzburg** [comment]
Thanks..so I will eliminate the delete and merge later tomorrow...

**Comment by Hwurzburg** [comment]
pixhack5 file re-instated....merged

**Pull request merged**
