### PR TITLE
SRXL2 and CRSF docs

### PR DESCRIPTION
**Pull request by andyp1per**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I know the CRSF PR is pending....when did SRXL2 support merge...cant find a PR open or closed with that in title

**Comment by Hwurzburg** [comment]
nevermind...typo in search

**Comment by Hwurzburg** [comment]
its already in the wiki by reference to this delayed merge PR in  the upcoming features/future wiki changes document
it will be merged when it appears in a release....all master only things are found in UPCOMING features....small things get put in the future wiki changes doc....big things by reference to their delay merge PR....

**Comment by 23suleyman** [comment]
Hello
I bought cf microtx v2 and nanorx pixhawk 2.4.8 and connected it from telemetry1 radio my radiomaster t16s
I configured ch1 and ch2 as mavlink
I have 2 problems
Yaapu doesn't show telemetry information on my radio
Couldn't connect to mission planner and qground on my computer with micro tx v2
The rc is OK and the radio comes with telemetry but it doesn't bring it to the screen.
I would be glad if you help

**Comment by Hwurzburg** [comment]
@23suleyman a PR is not the place to ask for support...please post your request in discuss.ardupilot.org support forums...thanks

**Comment by Hwurzburg** [comment]
merging..thanks

**Comment by Hwurzburg** [comment]
my rebase go out of hand...we need to chat...sorry

**Comment by andyp1per** [comment]
@Hwurzburg I had a copy - I redid the rebase

**Pull request closed without merging**
