### PR TITLE
Add UAV-DEV GmbH to common-commercial-support.rst

### PR DESCRIPTION
**Pull request by mirkix**
After starting my company UAV-DEV GmbH, I would be happy to be listed on the commercial support page. I have ArduPilot experience since 2015 and 145 accepted commits in ArduPilot.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Mirko....the requirements are shown at the bottom of the page....email with documentation requested
If you or your company wants to be listed here please email partners@ardupilot.org. To be added to this page we request the applicant has made a contribution to ArduPilot or a related project in some way. This includes code, documentation or helping people on the forums. The intention with this policy is to ensure that companies listed here will be active participants in the community.

**Comment by auturgy** [comment]
Mirko is on the dev team.
You’ll find him listed as a Maintainer here: https://github.com/ArduPilot/ardupilot/blob/master/README.md

He’s more than qualified for this page.

Regards,

James

**Comment by Hwurzburg** [comment]
super...will build check and merge!

**Comment by Hwurzburg** [comment]
built and merged...thanks....nice to meet you Mirko!

**Comment by mirkix** [comment]
@Hwurzburg @auturgy Thanks!

**Pull request merged**
