### PR TITLE
wiki: dependancies - Update building-ardupilot-onwindows10.rst

### PR DESCRIPTION
**Pull request by auturgy**
Fixes https://github.com/ArduPilot/ardupilot/issues/6945
Was stepped through with the author of the issue, but otherwise untested: someone should check this in a clean Windows or VM.

### CODE REVIEW

**Comment by OXINARF** [comment]
Related to #916 and #930. As I wrote in the latter one, keeping the old instruction is worth it for someone with an old WSL installation still running Trusty.

**Comment by auturgy** [comment]
Short memory. Sorry.
Will rewrite to just make some notes. Will take a few days

**Comment by EShamaev** [comment]
4.9.3.2015q3-1trusty1 is not available on latest WSL.
Also the "mount via the drvfs driver" does not help.

sudo apt-get install gcc-arm-none-eabi is working to build cloned in WSL copy, but still did not find a way to build the copy that is on Windows drive.

**Comment by auturgy** [comment]
Closing, as overtaken by rate of change.

**Pull request closed without merging**
