### PR TITLE
MAV_CMD_CONDITION_YAW: Enable rotation speed

### PR DESCRIPTION
**Pull request by muramura**
Copters support rotational speed.
I would remove the description of PARAM2.

Screenshot from 2020-11-03 11-17-46

### CODE REVIEW

**Comment by muramura** [comment]
I have reverted the formatting only changes back.

**Comment by Hwurzburg** [comment]
@rmackay9 review needed...thanks

**Comment by Hwurzburg** [comment]
@rmackay9 bump

**Review by rmackay9 — APPROVED** [review]

**Comment by Hwurzburg** [comment]
thanks...merging

**Pull request merged**
