### PR TITLE
common-planning-a-mission-with-waypoints-and-events.rst: implement #1435

### PR DESCRIPTION
**Pull request by vierfuffzig**
ping @khancyr

### CODE REVIEW

**Comment by rmackay9** [comment]
I wonder if this one is useful.. users's can't really set the 0th waypoint anywhere.. I'm not sure if they really need to know that it's the 0th waypoint..

**Comment by vierfuffzig** [comment]
added comment about this not being user settable

**Comment by khancyr** [comment]
@rmackay9 you can set it with custom IHM (or with ROS), or when loading a mission file. Easy mistake when you don't know MAVLink protocol ...

**Comment by rmackay9** [comment]
@khancyr, Not sure what an IHM is but in any case, using ROS isn't a very common use case for users and when loading with a mission file I'm not sure it's ever used.  I think I'll close this if that's OK.

**Comment by vierfuffzig** [comment]
@rmackay9 @khancyr the primary intention of this PR was to adress https://github.com/ArduPilot/ardupilot_wiki/issues/1435 
i'm perfectly fine with this approach being rejected, i'd appreciate alternative suggestions though.

**Pull request closed without merging**
