### PR TITLE
Update gsoc-ideas-list.rst

### PR DESCRIPTION
**Pull request by jmachuca77**
Add Swift package

### CODE REVIEW

**Comment by jmachuca77** [comment]
Yes, and I'll be willing to mentor and maintain, but would also like for the student to become involved in the project and maintain it. Our overall goal should be to capture more long term contributors, so that should not be a criteria to discard a project.
MAVSDK is already working and would be a matter of just adding ardupilot support, updating the pymavlink generator is more involved but its certainly doable in 3 months.

**Comment by auturgy** [comment]
Before tackling language specific bindings, the mavsdk-server would need to support ardupilot. I’ve had a very brief discussion with Jonas, the mavsdk maintainer, and he’s willing to assist if a GSoC student wants to take that on.

**Comment by jmachuca77** [comment]
Sounds good and better if they are willing to help with the support. I think that would be good for AP.

**Comment by rmackay9** [comment]
I've rebased separately and merged, thanks!

**Pull request closed without merging**
