### PR TITLE
dev: add a supported-mcu document

### PR DESCRIPTION
**Pull request by peterbarker**
Rough draft of document.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
needs to be included in a TOC list somewhere...perhaps learning-the-ardupilot-codebase

**Comment by Hwurzburg** [comment]
@peterbarker can we add the TOC entry and update the AP_Periph cpu list?

**Comment by nkruzan** [comment]
I doubt there is anyone that will keep this up-to-date with lead times and such, but I do like the idea of supported MCU list. Is there a way to generate the list from c++ code somehow? IE parse the filenames of https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32* to generate a table

**Comment by peterbarker** [comment]
On Sun, 6 Feb 2022, nkruzan wrote:

> I doubt there is anyone that will keep this up-to-date with lead times and such, but I do like the idea of supported MCU list. Is there a way to generate the list from c++ code somehow? IE parse the filenames of https://github.com/ArduPilot/ardupilot/tree/master/libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32* to
> generate a table

Perhaps.  I'm thinking of abandoning this concept at this point.  If I 
haven't gotten to it before now then I probably won't :-/

**Comment by Hwurzburg** [comment]
since this is listed in the porting docs already, do we need a separate page? shall I close?

**Comment by Hwurzburg** [comment]
@peterbarker  BUMP!

**Comment by Hwurzburg** [comment]
closing since page exists

**Pull request closed without merging**
