### PR TITLE
Added a link for pixhawk 2

### PR DESCRIPTION
**Pull request by proficnc**

### CODE REVIEW

**Comment by billbonney** [comment]
Do you have a new page for the pixhawk2 like this one https://github.com/proficnc/ardupilot_wiki/blob/master/common/source/docs/common-pixhawk-overview.rst

**Comment by billbonney** [comment]
@proficnc I have added the DRAFT page here for you to edit https://github.com/ArduPilot/ardupilot_wiki/blob/master/common/source/docs/common-pixhawk2-overview.rst

you can update your PR to link to this page when you have it ready. i.e. 

```
     Pixhawk <common-pixhawk-overview>
 +    Pixhawk2 <common-pixhawk2-overview>
      Pixracer <common-pixracer-overview>
```

Hope that helps :)

**Comment by proficnc** [comment]
For the longer term, yes, but in the short term, I would rather it pointed to the Pixhawk QuickStart as it will get people going.

**Comment by billbonney** [comment]
Your link just points to the Pixhawk Overview, not the quickstart guide. You can add quick start guide link to the new Pixhawk2 Overview page and indicate its to get you started until PH2 is ready,  ie.Work In Progress.

**Comment by billbonney** [comment]
@proficnc You just need to add the proper specs to the page, then we can enable it in the index. I added an image and links to QuickStart and your homepage

http://ardupilot.org/copter/docs/common-pixhawk2-overview.html

**Comment by rmackay9** [comment]
I've taken @billbonney's page and added some more to it.  sadly I accidentally blasted bill's name as the committer :-(.  Still, a page is there now so I'm closing this.  Txs!

**Pull request closed without merging**
