### PR TITLE
retire how-to-use-the-auth-command-to-sign-a-pixhawk-board-with-your-…

### PR DESCRIPTION
**Pull request by davidbuzz**
…certificate-of-authenticity.rst

### CODE REVIEW

**Comment by Hwurzburg** [comment]
archiving this page is probably a better approach, agreed?

**Comment by peterbarker** [comment]
On Wed, 28 Apr 2021, Henry Wurzburg wrote:

> archiving this page is probably a better approach, agreed?

Yep.

**Comment by Hwurzburg** [comment]
I'll put it on my list

**Comment by Hwurzburg** [comment]
closing...page has been archived....thanks

**Pull request closed without merging**
