### PR TITLE
Rover mower 3

### PR DESCRIPTION
**Pull request by SAJohnson1503**
Pull request to add image from my github account

### CODE REVIEW

**Comment by Hwurzburg** [comment]
nice start! a lot of work yet to be done, of course....I would think the most important information for a topic like this is some examples of the mechanics of converting a mower to servo control of steering and speed....that information is the key for this to be a useful topic addition.... the ArduPilot Rover system has a lot of existing information....pulling that, together with some real examples guiding the development of the servo mechanics, would be the extension of the existing information that autonomous mowers need in the wiki

**Comment by SAJohnson1503** [comment]
improper request

**Comment by SAJohnson1503** [comment]
Hey Henry, thanks for your comments. It would be easy to add examples of
the mechanics as you mentioned. I assume you must be part of the
development team to intercept a pull request. I was just surprised, Yuri
has been my contact. I am just a user who has become immersed in the mower
community, including building my own mower. Right now I am having a tough
time trying to get some images uploaded. I have been able to add text just
fine by submitting submit pull requests but I have not found out how to get
images uploaded. I try submit pull requests and to get them uploaded and it
always indicates I don’t have permission to ask for a PR to upload images.
I am not a software guy so GitHub and the whole editor is something I am
learning. I am a retired electrical engineer who likes to build things.  I
am one of the guys who helps all the struggling mower builders trying to
build a mower. I know the problems they have. This WIKI will be top quality
when we are done and get it pulled together and reviewed by the experts in
the field.

**Comment by Hwurzburg** [comment]
I am the Wiki Maintainer, responsible for the wiki....if you are having problems with adding images, I can help...but I will be out of town for the next 10 days or so...otherwise, I could meet you on discord and walk you thru the process if you are having issues...when I return I can help

**Comment by SAJohnson1503** [comment]
Thanks Henry,  I will see how it goes.  I know Yuri is also too busy to
help right now also. Anyway, I will keep trying to work something out and
asking around. I just need permission to place a pull request to add images
to the rover image folder that Yuri is working with.

**Pull request closed without merging**
