### PR TITLE
Dev/Common: camera and gimbal updates

### PR DESCRIPTION
**Pull request by rmackay9**
This PR includes camera and gimbal related updates for both the developer and user wikis.

The developer wiki gets details on new commands supported in AP-4.5.0

The user wiki gets warnings and fixes for the Siyi and Gremsy gimbals.

This has been tested locally and seems OK.

### CODE REVIEW

**Comment by rmackay9** [comment]
I'd accidentally committed some changes to the build options file which I've removed now.  Sorry about that.

**Comment by rmackay9** [comment]
Hi @Hwurzburg,

Thanks for that.  I think we should consider merging this before 4.5 is ready because many developers work off of master.  Also the non-dev changes are valid for 4.4.

**Comment by Hwurzburg** [comment]
the non dev changes state 4.5 or higher....not 4.4....a mistake? if not, we can split them out as 4.5 and merge the dev only stuff...I am okay with that

**Comment by rmackay9** [comment]
Hi @Hwurzburg,

I've removed the Gremsy 4.5.0 related change and will put that in a separate PR.  I think the rest of the changes are development (which can go in even though the stable version is not 4.5 yet) or are user wiki changes not related to 4.5.

**Comment by Hwurzburg** [comment]
Thanks...merging

**Pull request merged**
