### PR TITLE
Update common-here-plus-gps.rst + images

### PR DESCRIPTION
**Pull request by smullolo**
The common-here-plus-gps.rst has been updated. The necessary images for the update have been added to the image folder. All added images start with HERE+.

### CODE REVIEW

**Comment by auturgy** [comment]
@proficnc can you review?  This looks like a great contribution, but needs a knowing eye to check it.

**Comment by caomuqing** [comment]
The content is copied directly from the official HEX HERE+ documentary that can be found at http://www.hex.aero/?page_id=236 . In fact, @smullolo is helping HEX to update the wiki from existing documentary. Therefore it should have no issues.

**Comment by auturgy** [comment]
Quick observation: QGC does support Here+,  so that needs to be clarified in the opening paragraph.  When was the Hex wiki last updated?  If there are areas of the Hex source document that are outdated, this will be outdated too.  Things progress quickly!

**Comment by caomuqing** [comment]
This wiki was last updated in mid August. I helped to draft the wiki, and so far it is not outdated yet. @smullolo  will edit the opening part about QGC again.

**Comment by OXINARF** [comment]
I haven't read all of it, but this needs a squash, looks like one, maybe two, commits is enough.

**Comment by proficnc** [comment]
A “squash” may make sense to software developers, but means nothing to the
rest of us....
any hints for these guys?

**Comment by auturgy** [comment]
I had to learn this too, and often forget.  
git reset --soft HEAD~N  // N = number of commits to reset
git commit -m "New message for the combined commit"
git push origin +name-of-branch  // the + is important

**Comment by hdtechk** [comment]
if this is from the Hex pdf. most people on facebook group having trouble updating firmware. have had 
the send training check box checked.  and when they turn it off then firmware update works.  So is it really
needed?

**Comment by smullolo** [comment]
I have squashed all the commits together.

**Comment by auturgy** [comment]
@smullolo thanks very much!
having a look, shouldn't be long: this is an important update

**Comment by auturgy** [comment]
I'm merging this, because it is important to make the information accessible.
For users and contributors: Progress is fast.  If we need to update this guide, please raise an issue or make a pull request, via the links on the page.
For @smullolo thanks for your efforts.  Git takes a bit of practice, and I'm very much a novice myself.  If you have questions re github and staging commits, please visit https://gitter.im/ArduPilot/ardupilot_wiki and ask as many questions as you need to.  We will do our best to help.

**Comment by caomuqing** [comment]
thanks guys, great work.

**Pull request merged**
