### PR TITLE
Added FlyFix to commercial support page

### PR DESCRIPTION
**Pull request by yaadc**
Added FlyFix to commercial support page.

### CODE REVIEW

**Comment by auturgy** [comment]
Thanks Yaad,
we’re still discussing this internally: I wanted to get the discussion onto GitHub rather than the limited visibility of email: I think it will help make it clearer for how we manage this page in the future.

Regards,

James

**Comment by Hwurzburg** [comment]
Sorted all in alphabetical order by country/vendor per normal convention

**Comment by yaadc** [comment]
Thanks, let me know if anything else should be done.

**Comment by tridge** [comment]
@yaadc as we say on that page, we only add companies who have made a contribution to ArduPilot in some form (code, documentation, support on forums etc). Can you please describe the contributions that FlyFix have made?

**Comment by Hwurzburg** [comment]
stale...closing

**Pull request closed without merging**
