### PR TITLE
Common: simplify camera servo and camera relay setup instructions

### PR DESCRIPTION
**Pull request by rmackay9**
This simplifies/clarifies the camera setup when using servo or relays.

I've removed a picture and perhaps that means we could remove the pic from the images directory as well, but sometimes we use images across pages.

I've tested it locally and it looks OK to me.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Going to take till the weekend for me to list all the changes required....lots of interdependencies not covered here that will direct people to ARCHIVED pages and pages archived need to be marked as such...and you are right lots of pages use those figures, perhaps incorrectly now and also need changes??

**Comment by rmackay9** [comment]
I just noticed a small spacing issue so I've re-based and re-pushed.

@Hwurzburg, OK, I'll try and do a search for references to the archived pages.

**Comment by Hwurzburg** [comment]
I have updated sections using CHDK, added archive titles, tweaked spelling in servo doc....figure is used elsewhere so cant delete...
if everything is okay, I will merge this...thanks

**Review by rmackay9 — COMMENTED** [review]
Looks good to me. Thanks!

**Pull request merged**
