### PR TITLE
Add new rangefinders

### PR DESCRIPTION
**Pull request by rishabsingh3003**
Added docs for:
Nooploop TOF Sense P
Nooploop TOF Sense F
NanoRadar NRA24 (CAN)

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@rishabsingh3003 thanks....cleaned up build errors and typos, made format consistent, and some minor wordsmithing....adding link to this PR in upcoming features of wiki

**Comment by rishabsingh3003** [comment]
@Hwurzburg Thanks!! 
Documentation would be so much tougher without your support :)

**Comment by rmackay9** [comment]
Hi @Hwurzburg, what are the remaining bits that you think need fixing before we merge this?  is it just that we need to still add link to this PR in upcoming features of wiki?

**Comment by Hwurzburg** [comment]
nothing...but it wont merge until 4.5 beta.,...its already linked in wiki under upcoming features

**Comment by rmackay9** [comment]
@Hwurzburg,

OK, thanks.  somehow I put my comment on PR https://github.com/ArduPilot/ardupilot_wiki/pull/5472 instead of this one.

I think for new page (as opposed to changes to existing page) it would be good to get them into the wiki before beta testing starts even if only linked from the upcoming features section.  A link to a PR isn't of much use to users because they will give up trying to understand the RST.. they need a page that they can just look at.

I'll leave it with you but I think there's value in having the wiki pages already readable for alpha testers, developers, the sensor company, etc.

**Comment by Hwurzburg** [comment]
okay I will try to split this up and link pages on upcoming instead of futures when I can

**Comment by Hwurzburg** [comment]
merged the individual RF pages and linked from upcoming page...this doc will be added when the pages are removed from upcoming on 4.5 beta

**Comment by rmackay9** [comment]
@Hwurzburg,

Thanks very much!

**Pull request merged**
