### PR TITLE
Create setting-up-sitl-on-linux.rst

### PR DESCRIPTION
**Pull request by muhammedozel**
python-wxgtk2.8 has been changed vith python-wxgtk3.0 and writing python-wxgtk2.8 cause error

### CODE REVIEW

**Comment by OXINARF** [comment]
These instructions should be updated to tell developers to use our installer script, but maybe until that is done it is indeed better to show a command line for the latest OS versions.

I'll let other wiki maintainers share their thoughts.

**Comment by magicrub** [comment]
Does this require python 3.x?

**Comment by OXINARF** [comment]
No, it's the wxgtk that was updated to version 3.0 and 2.8 isn't available in more recent OS versions.

**Comment by muhammedozel** [comment]
It has to be changed because of beginner user gets an error and they won't understand what is the issue?

**Comment by OXINARF** [comment]
@muhammedozel Yes, but a user with an older OS version will get the error too since 3.0 doesn't exist there. Anyway, I've merged, thanks!

**Pull request closed without merging**
