### PR TITLE
Update common-storm32-gimbal.rst

### PR DESCRIPTION
**Pull request by Kigurai**
Added warning about RF interference from Storm32 boards.

### CODE REVIEW

**Comment by OXINARF** [comment]
@olliw42 Do you want to comment on this?

**Comment by lvale** [comment]
@OXINARF I can NOT confirm this. I've tested several boards with a RF Explorer and haven't seen any noticeable interference results on the common frequency ranges (433M, 868M, 900M, 1.2G, 2.4G, 5.8G). We have several of these units in industrial environments in production all around the world, so it is important to verify these issues.

**Comment by olliw42** [comment]
hey, thx oxinarf, and thx luis
a comment could be appropriate; some such instance were reported
I however think that the note is somewhat imprecise, and also could point to solutions
the OP should adapt the text to reflect the situation more correctly, IMHO

**Comment by Kigurai** [comment]
It's quite clear from the discussion on RCG that it has been an issue for
several people.
 I added the note as warning (and Ollie even thanked me for it on RCG).

**Comment by lvale** [comment]
My testing does not confirm your statement. I might have misused the testing equipment (RF-Explorer), so please confirm with some measuring equipment.

**Comment by Kigurai** [comment]
Here's Ollie himself confirming it:
https://www.rcgroups.com/forums/showpost.php?p=37930438&postcount=10018

Here's another user testing it on the 433mhz
https://www.rcgroups.com/forums/showpost.php?p=34132760&postcount=579

I have no equpment for testing it against the 915mhz band, but both myself
and another user were unable to reliably connect with the 915mhz telemetry
radios with the gimbal running.

Now, given that safety is always a overriding issue, don't you think it
would be prudent to put up a warning on a product that the developer
himself has repeatedly stated is a hobby project and should not be expected
to perform to professional standards?

Further, if Ollie wants to add solutions, he can add them himself.

**Comment by lvale** [comment]
Had a STorM32 over here and redid a testing (only one unit so not very relevant) and the difference with the RF Explorer antenna right on top of a STorM32 is very small with or without power. Biggest relevant difference is around the 350MHz

img_20170723_030058

**Comment by lvale** [comment]
I just checked and there's a notice on the STorM32 wiki about an issue with RF noise, and also a solution to the problem is pointed, but only on a very specific board variant.
https://www.rcgroups.com/forums/showpost.php?p=34139984&postcount=585

http://www.olliw.eu/storm32bgc-wiki/STorM32_Boards


If you don't mind rephrasing your comment and pointing to the solution it would be beneficial to other users.

**Comment by goandfix** [comment]
Hello all, I have both boards. Someone could confirm if I can use the GLB STorM32 v1.31 without issue into 433mhz band? Thank you

**Comment by lvale** [comment]
Just in case your STorM32 has a RF noise issue follow these recommendations
https://www.rcgroups.com/forums/showpost.php?p=34139984&postcount=585

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
