### PR TITLE
Small grammatical changes

### PR DESCRIPTION
**Pull request by ThisIsTheOnlyUsernameAvailable**
* Include Cube in flight controller mounting
* Remove defunct online stores
* Add Cube overview page
* Grammatical change in the wiki editing page
* Updated events page

### CODE REVIEW

**Comment by auturgy** [comment]
Lets hold on this: cuav.net is gone, but they still have an online store through alibaba.  Need to check with them.

**Comment by auturgy** [comment]
Also, changing the page name from pixhawk2-overview to thecube-overview needs to have a few other associated changes: basically any pages that link to it also need updating.  Can you do that, on this branch?

**Comment by auturgy** [comment]
This needs to go in now I've merged the bulk of the associated PR's.  If any of the links have been missed, they'll need to be fixed.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Will do.  I'll do a full search for any remaining links to the PH2 and bundle the changes with the removal of pixhawk2-overview.

**Pull request merged**
