### PR TITLE
fix wiki build error in DEV

### PR DESCRIPTION
**Pull request by Hwurzburg**

### CODE REVIEW

**Comment by rmackay9** [comment]
MAG_ENABLE still exists in the stable branches so I think this should be delayed until the next release or we should just remove the reference for MAG_ENABLE for now.

**Comment by Hwurzburg** [comment]
de-ref'd...thanks

**Comment by rmackay9** [comment]
.. looks like a little typo has crept in though, it's MAG_EN instead of MAG_ENABLE..

**Comment by Hwurzburg** [comment]
duh.....

**Comment by rmackay9** [comment]
Merged, thanks!

**Pull request merged**
