### PR TITLE
Create common-osd-overview.rst

### PR DESCRIPTION
**Pull request by vierfuffzig**
Adds a basic documentation for AP_OSD library, focussed on use with FCs featuring onboard MAX7456-type chipsets.

### CODE REVIEW

**Comment by rmackay9** [comment]
I guess this should be added into the Optional Hardware section?

**Comment by vierfuffzig** [comment]
thanks for checking this!
i was unsure where to link this page, i'd say optional hardware too.
added image and fixed top line.

**Comment by khancyr** [comment]
Nice !
Do you think you can add SITL version too for  people that want to test with material ?

**Comment by vierfuffzig** [comment]
thanks khancyr! 
thorough documentation of SITL implementations is actually somewhat beyond my scope right now, i'd have to work myself through this first. could we maybe leave that for future improvements?

**Comment by vierfuffzig** [comment]
added SITL references

**Comment by rmackay9** [comment]
Someone in the Copter-3.6 thread is asking about the OSD so seems like a good time to merge it.  I think we should probably create a new section for video and OSD stuff under the Optional Hardware section but we can do that as a follow-up change.

**Pull request merged**
