### PR TITLE
Common: add djirs2 gimbal support to upcoming features

### PR DESCRIPTION
**Pull request by rmackay9**
This adds a wiki page to go with the new DJI RS2 gimbal support. https://github.com/ArduPilot/ardupilot/pull/22776

Note that the Siyi A8 support has been released with 4.3 so I've removed it from the upcoming features.

This has been tested on my local machine and looks OK.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@rmackay9 we need to understand why your local build is not showing the significant wiki build error that this creates when you tested this PR locally...it leaves the SIYI page "floating" (not in a TOCTREE)....it must be linked on the camera and gimbals page in the bottom toctree....

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
fix toctree build error

**Comment by rmackay9** [comment]
@Hwurzburg,

Txs for the review.  I've fixed the missing toc now and I don't see build errors any more.

**Comment by Hwurzburg** [comment]
thanks...

**Pull request merged**
