### PR TITLE
update.py: option to build only selected wikis

### PR DESCRIPTION
**Pull request by peterbarker**
e.g. time ./update.py --cached-parameter-files True --wikis copter

### CODE REVIEW

**Comment by peterbarker** [comment]
This overlaps with `--site`; one or the other should die.

**Comment by hamishwillee** [comment]
@peterbarker FYI Where we need improvements in the script is the way that common files are handled. 

At the moment, (prior to a build) the script deletes all common files from the individual wiki source trees then copies in the current set. While this guarantees that the individual wikis contain the latest common files, it means that incremental builds do not work. Everything gets rebuilt, even though most things haven't changed.

**Comment by peterbarker** [comment]
On Wed, 10 May 2017, Hamish Willee wrote:

> At the moment, (prior to a build) the script deletes all common files from
> the individual wiki source trees then copies in the current set. While this
> guarantees that the individual wikis contain the latest common files, it
> means that incremental builds do not work. Everything gets rebuilt, even
> though most things haven't changed.

Why does the remove/copy step negate incremental building?  Are we not 
preserving timestamps while copying the files?

**Comment by hamishwillee** [comment]
I don't know, I just know that incremental builds no longer happen.

**Comment by peterbarker** [comment]
https://github.com/ardupilot/ardupilot_wiki/blob/master/update.py#L98

I think that's a likely reason for the lack of incremental builds:-)

I think you're well placed to get into the head of the person who added that line....

Removing the line drops build time from ~1m30s to 30s - I've no idea if the build is correct, however.

**Comment by hamishwillee** [comment]
The guy who made that change was probably an idiot :-) Previously this had clean as a separate step.

I think that I wasn't sure how well the system would handle a non-clean build with "old" artifacts. My original plan was to at least see if a common page had been added/removed. Anyway, this is something that certainly is worth testing.

**Comment by tomlauzon** [comment]
this has been my nightmare... can it be fixed?

**Comment by hamishwillee** [comment]
Anything can be fixed, but I don't have the bandwidth to think about it right now.

**Comment by peterbarker** [comment]
On Fri, 12 May 2017, tomlauzon wrote:

> this has been my nightmare... can it be fixed?

Are you in a position to test patches?

It is possible things will just work with 
https://github.com/peterbarker/ardupilot_wiki/tree/no-clean

... but being a kinda hacky build process we might find that things don't 
get rebuilt appropriately.  The clean was almost certainly put in 
originally because someone got annoyed with things *not* getting rebuilt!

**Comment by hamishwillee** [comment]
> The clean was almost certainly put in originally because someone got annoyed with things *not* getting rebuilt!

Probably not actually. I think I put it in because I was finishing my contract and wanted things to be robust.

**Pull request closed without merging**
