### PR TITLE
Update motor-thrust-scaling.rst: Warning for Tmotor ESC users

### PR DESCRIPTION
**Pull request by MallikarjunSE**
Many users on forum are facing issues with tmotor escs. Thought to add this bit.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
could you give  a link to issues being reported? and solutions proven? thanks

**Comment by MallikarjunSE** [comment]
https://discuss.ardupilot.org/t/what-should-i-use-for-atc-rat-pit-flt-values/49768/36?u=mallikarjun_se

**Comment by MallikarjunSE** [comment]
https://discuss.ardupilot.org/t/mot-thst-expo-setting-for-t-motor-flame-escs/27747

**Comment by Hwurzburg** [comment]
@MallikarjunSE  this needs to be generalized....since you restricted access to this PR I cant push changes to it...so I created a new one #3101...
if you wish to retain commit authorship, you can pull that PR down and force it over your patch-1 branch, or go allow access to this PR and I will puch over it....if you are not comfortable with that, I will need to close this one and merge 3101....
thanks

**Comment by Hwurzburg** [comment]
will merge the other one...thanks

**Pull request closed without merging**
