### PR TITLE
dev: Add ROS 2 documentation

### PR DESCRIPTION
**Pull request by pedro-fuoco**
The purpose of this PR is to add a ROS 2 page, similar to the current [ROS](https://ardupilot.org/dev/docs/ros.html) page on `ardupilot_wiki`. The page `<ros2-sitl>` was added to get users started.

I am also on working on `<ros2-gazebo>` and `<ros2-gazebo-slam>` for future PRs.

Although I haven't found a way to do it, the ROS 2 page should sit next to the ROS index in the dev menu:
image

### CODE REVIEW

**Comment by Hwurzburg** [comment]
if @rmackay9 signs off on the technical stuff, I can work on formatting and integrating into the dev wiki....I think one ROS landing page with links to ROS and ROS2 documents is the way to go to keep clutter down on the first level menu...its on my to-do list to simplify it like we did for the vehicles...

**Comment by pedro-fuoco** [comment]
@Hwurzburg sounds good, thanks for the quick review! 
@rmackay9 the technical stuff has been heavily based on READMEs from @Ryanf55 and @srmainwaring and are linked on the pages.

**Review by rmackay9 — APPROVED** [review]

**Comment by Hwurzburg** [comment]
reformated, corrected build errors, reorganized and added into existing ROS wiki

**Comment by Hwurzburg** [comment]
thanks!

**Pull request merged**
