### PR TITLE
partners: added vimdrones

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by rmackay9** [comment]
Merged, let's see how it looks on the real page

**Comment by Hwurzburg** [comment]
after six hours, I dont see it yet on the build...did our build frequency drop?

**Comment by rmackay9** [comment]
I see that the "pretty" page has updated: http://ardupilot.org/about/Partners, but as you say it hasn't appeared in the common-partners page.  http://ardupilot.org/copter/docs/common-partners.html

By the way it looks like the common-partners page is not-found if accessed from the index page:
  - index: http://ardupilot.org/copter/index.html (see "Partners" down on the bottom left)
  - http://ardupilot.org/ardupilot/docs/common-partners.html <-- 404 error

**Comment by proficnc** [comment]
On a mobile http://ardupilot.org/about/Partners is missing 2/3 of the partners

**Pull request merged**
