### PR TITLE
Add exception message for vimeo module

### PR DESCRIPTION
**Pull request by TunaLobster**
Should cause an issue if the module is present and not just build without Vimeo videos included.

@peterbarker The issue should be easier to spot now.

### CODE REVIEW

**Comment by TunaLobster** [comment]
Tested with python 3.8 with and without the sphinxcontrib.vimeo module installed.

**Comment by TunaLobster** [comment]
This should not go in yet. Need to wait on a few other PRs to get the Vimeo part correct and to get the YouTube plugin working.

**Comment by Hwurzburg** [comment]
@TunaLobster  @peterbarker ready now?

**Comment by TunaLobster** [comment]
No. This was meant to be a follow up PR for #35755. But that has been reverted. Then I had to fix something in the plug-in repo so that it would work with python 2.7 and sphinx 1.8. Now I'm wait for the new venv things to get settled before trying to remove this dependency. I might also have to wait until we update the sphinx version which will also be dependent on updating the theme. Now I need to reopen a PR that includes several other things, including this one, but I won't do that until everything is ready because I don't want something to be merged into master without you testing it and have it upset the build.

**Pull request closed without merging**
