### PR TITLE
RNGFND1_MIN_CM reference fix

### PR DESCRIPTION
**Pull request by brunoolivieri**
Fix broken parameter reference due issue #1869.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
this needs to wait until multiple RNGFNDR appearss in betas....also, you should say something like,

T"he solution is, for example in the case of the first rangefinder,  to reduce the :ref:`RNGFND1_MIN_CM <RNGFND1_MIN_CM>` value (to perhaps "5").

**Comment by brunoolivieri** [comment]
Done and rebased, thanks.

**Comment by Hwurzburg** [comment]
Hey Bruno, do you mind if I close this? we were working at the same time and #1954 fixes this and a bunch more....its easier to close this than extract it from #1954 to avoid a future merge conflict....

**Comment by brunoolivieri** [comment]
Sure, no problem. Closing...

**Pull request closed without merging**
