### PR TITLE
Include a free lua script alternative

### PR DESCRIPTION
**Pull request by jplopezll**
FlightDeck is not free, I am proposing the inclusion of a free alternative.

### CODE REVIEW

**Comment by auturgy** [comment]
If you could update this with the <> around your web address so the hyperlink will render, I’m happy to merge this.
For clarity and history, this is a separate work from that subject to DMCA debate in dapo.

**Comment by lvale** [comment]
Thanks for the PR @jplopezll . I'm sorry I didn't do one pointing to it before.

**Comment by tomlauzon** [comment]
Looks good. No objection other than the <> as mentioned by @auturgy. Great to have more options.

**Comment by magicrub** [comment]
merged, thank you!

**Comment by jplopezll** [comment]
Hey, that was fast! Thanks a lot to all. Happy to contribute.

**Pull request merged**
