### PR TITLE
Add info about Navio2 to AutoPilot Hardware Options

### PR DESCRIPTION
**Pull request by i-smirnov**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@i-smirnov What this is missing is a link to where you can purchase the product and your site. My only other  thought is whether the image could be slightly lower resolution - we're on github now so good to store smaller files. There is probably some minor tweaking that could be done to wording and layout, but this is really good - thanks!

PS You might also want to update [supported autopilot boards](https://github.com/ArduPilot/ardupilot_wiki/blob/master/dev/source/docs/supported-autopilot-controller-boards.rst) on dev wiki and create an equivalent topic to [Building for Navio on ...](http://ardupilot.org/dev/docs/building-for-navio-on-rpi2.html?)

@rmackay9  Please review too!

**Comment by i-smirnov** [comment]
Hi guys! I force pushed some edits: 
- fix little typos
- reduce image resolution
- add links

I will update 'supported boards' and 'APM building' sections in the next few days. Thanks!

**Comment by hamishwillee** [comment]
Thanks @i-smirnov - looks good.

@rmackay9 This is basically good by me. Can you do a quick review and press the merge button if you are OK with it?

**Comment by rmackay9** [comment]
done!

**Pull request merged**
