### PR TITLE
added ModalAI Flight core to supported hardware

### PR DESCRIPTION
**Pull request by Matt-Lohier**
updating our docs per your request!

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I am afraid that directing ArduPilot users to a product that is 100% branded PX4 and makes no mention of ArduPilot would be confusing to them....I assume that you intend to update the website and descriptions to include ArduPilot in the very near future?
ultimately, I would like to produce a wiki page for this controller just like the other autopilots, rather then having an offsite link...

**Comment by Matt-Lohier** [comment]
Thank you for your reply! We intend to add Ardupilot documentation to our site in the very near future but have other documentation priorities for the time being. 
I'll be circling back to this soon.
Thanks!

**Comment by Hwurzburg** [comment]
@Matt-Lohier any progress?

**Comment by Matt-Lohier** [comment]
Hi @Hwurzburg 
For now, no progress. 

The engineers at ModalAI do not have experience with ArduPilot, so for now we can't 'officially' offer any support on our end. We have begun adding documentation for ardupilot on our docs [Here](https://docs.modalai.com/flight-core-firmware/#ardupilot) based on the wonderful work the ardupilot community has done. ModalAI is currently focusing on some important product launches early this year but ardupilot integration remains a priority.

**Comment by Hwurzburg** [comment]
I see you are a partner now and the board does mention AP, thanks....I have rebased and merged a link to your autopilot in #4758 thanks

**Pull request closed without merging**
