### PR TITLE
common: update prearm check explanations

### PR DESCRIPTION
**Pull request by rmackay9**
This adds a table of pre-arm checks that may be displayed to users along with a "Cause" and "Solution".

This covers pretty much all non-vehicle specfic arming checks and Copter specific checks.  I.e. Plane, Sub and Blimp specific checks are not yet covered.

I've tested this locally now and it looks OK to me.

@Hwurzburg maybe we could merge this after you move a few of the most common items to the top?  I might move a few up in a future PR.

It's hard to say if this massive table will be useful for not but I hope that if it is complete and provides enough detail for each failure that it will slightly reduce the number of support calls or at least give us a page to point newbies at when they ask what a failure message means.

### CODE REVIEW

**Comment by Hwurzburg** [comment]
I think getting a more complete listing of the pre-arm messages and suggested resolutions is a good thing...by table or by line items as is the current format....
I dont think tabularizing them will help anyone find their pre-arm message....the wiki search box will take each component word of the phrase and match EVERY instance in the wiki of each word, unfortunately....
I do think that they should be grouped by at least the most commonly encountered messages and ones with most unobvious solutions first ..... eg. AHRS: not using configured AHRS type, ...EKF3 Roll/Pitch inconsistent by x degs...etc.

btw, there is one  message I see often but cant seem to find in the code: Terrain data missing or unavailable.....or something to that effect until the GPS gets a fix.....I dont use Terrain for navigation but do display the alt in OSD...maybe someone can find it

**Comment by rmackay9** [comment]
Hi @Hwurzburg,

OK, I'll continue and complete the list.  This PR already includes nearly everything from AP_Arming.cpp and the libraries that it calls so it is just the vehicle specific messages that are missing.

Re grouping, I'll just do it alphabetically then if that's OK.  Most related messages will end up grouped together but there will be a few which are out-of-place but then maybe those messages should be fixed instead.

**Comment by Hwurzburg** [comment]
are you going to add Rover and Plane's?

**Comment by rmackay9** [comment]
Hi @Hwurzburg,

I'm going to add Rover at least but in a follow-up PR if that's OK.  I might leave Plane out 'cuz I'd just be guessing the solution half the time.

**Comment by Hwurzburg** [comment]
so its ready for merge as far as you are concerned? I will add the Plane arming this weekend and move a couple items up after its merged, if you are ready

**Comment by rmackay9** [comment]
@Hwurzburg,

Yes, I think this is ready to merge.

**Pull request merged**
