### PR TITLE
Added AIRLink hardware description

### PR DESCRIPTION
**Pull request by aviaks**
Created hardware page and added description for AIRLink.

### CODE REVIEW

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
very nice hardware....a few comments:
There is information that we usually provide on this page( which is not on your website instructions either) for:
    - UART ordering
    - RC input connections and protocol setup
    - Output timer groups, ie which have to have the same protocol/timing, & which outputs support Dshot, BLHeli passthru
    - pointer firmware downloaded from firmware.ardupilot.org (only downloads from your site are given instructions)
see for an example https://ardupilot.org/copter/docs/common-matekf405-wing.html

**Comment by tridge** [comment]
a defaults.parm would be worthwhile, yes

**Comment by aviaks** [comment]
@Hwurzburg thanks! Missing information has been added. 
A small comment - the link to Firmware at https://ardupilot.org/copter/docs/common-matekf405-wing.html is actually leading to 404 at the moment. 

@tridge thanks! I'll add defaults.parm as a separate pull request in firmware repository.

**Comment by Hwurzburg** [comment]
@aviaks very strange...the link in the document is correct...something is wrong in the wiki....will investigate

**Comment by aviaks** [comment]
> @aviaks edit: found the issue...bad link formation...will update all

Ok, great to hear it's resolved now!

**Comment by aviaks** [comment]
> a defaults.parm would be worthwhile, yes, especially for the serial setup for companion computer

Default parameters file added in https://github.com/ArduPilot/ardupilot/pull/19277

**Comment by Hwurzburg** [comment]
LGTM....thanks..merging

**Comment by aviaks** [comment]
@Hwurzburg awesome, many thanks!

**Pull request merged**
