### PR TITLE
Use autopilot-agnostic language

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by rmackay9** [comment]
Looks good to me.  I wonder if there is a difference between "autopilot" and "flight controller" and whether we should tend to use one or the other.

**Comment by Hwurzburg** [comment]
I try to use autopilot everywhere....Antenna Trackers and Rovers usually do not fly

**Comment by nkruzan** [comment]
Nice to see tracker getting some love ;)

**Comment by peterbarker** [comment]
I've changed this to just be "autopilot", not "flight controller".

**Comment by Hwurzburg** [comment]
thanks!

**Pull request merged**
