### PR TITLE
Common: Add a new partner BZB UAS

### PR DESCRIPTION
**Pull request by rishabsingh3003**
This has been requested by a new partner

### CODE REVIEW

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
did not add the logo itself

**Comment by rishabsingh3003** [comment]
Okay, this was embarrassing .. I forgot to commit the logo before pushing 😅

**Comment by Hwurzburg** [comment]
thanks....merging... did not know there was a UAV company in Poland...will have to visit them the next time I am in Wroclaw

**Comment by rishabsingh3003** [comment]
Thank you!

**Pull request merged**
