### PR TITLE
Add get involved page

### PR DESCRIPTION
**Pull request by brunoolivieri**
This PR tries to solve issue #652. Would be something like that @rmackay9?

I still need to include it on some toctree. Where could I link it? May be in vehicles home pages?

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Bruno, good idea! I think it should be integrated somehow on the ardupilot.org/index.html page though

**Comment by rmackay9** [comment]
By the way, we have this "contact us" page which has some similar info on it. http://ardupilot.org/dev/docs/common-contact-us.html

**Comment by brunoolivieri** [comment]
Indeed the "contact us" pages have a similar idea. Makes sense create another?

Anyway, I updated the PR  with your comments.

What do you think?

**Comment by brunoolivieri** [comment]
Update: As discussed in the last Wikicall, there were many repetitions. We discuss in do not add a new page, but add a link to actual pages.

**Comment by brunoolivieri** [comment]
I guess the [PR 10 on sphinx theme](https://github.com/ArduPilot/sphinx_rtd_theme/pull/10) handles the discussed in last wikicall.

The we merge that I think we could close this PR ignoring these proposals.

**Comment by Hwurzburg** [comment]
yes....we will close this one...the Sphinx PR is best way to go...I requested a small change....I can test it once its done....

**Comment by brunoolivieri** [comment]
sure, thanks

**Pull request closed without merging**
