### PR TITLE
Update learning-ardupilot-storage-and-eeprom-management.rst

### PR DESCRIPTION
**Pull request by Kametor**
This link gives 404 error, the directory was changed but not edited in wiki i think

### CODE REVIEW

**Comment by Hwurzburg** [comment]
@peterbarker Peter, could you look at this? while the link is wrong, the entire description I believe is now inaccurate also...does not seem to match the code example...who should revise this?

**Comment by peterbarker** [comment]
@Kametor @Hwurzburg I'm afraid the new link is wrong, too.

DataFlash was the old name for `AP_Logger` - we retained the name `DataFlash` well past the time it was correct as for a long time we only supported writing files to POSIX-style filesystems or over mavlink.  Now we *can* write to dataflash again - but that's relatively new....

So, sadly, it's probably my job to fix any innaccuracies.

The correct link would be to `libraries/AP_Logger/examples/AP_Logger_test/AP_Logger_test.cpp`


However, the entire page probably needs splitting up; the logging is no longer intrinsically linked with the Storage layer (which is basically why "eeprom" in there is talking about....

**Comment by Kametor** [comment]
@peterbarker  so should I close this PR? or close after changing the link with you suggested?

**Comment by Hwurzburg** [comment]
@Kametor leave open... I will occasionally ~~annoy~~ remind Peter to update the page based on this PR being open

**Comment by Hwurzburg** [comment]
@peterbarker consider yourself ping'd ;-)

**Comment by peterbarker** [comment]
@Kametor @Hwurzburg Let's just correct the link and commit it....

**Comment by Hwurzburg** [comment]
okay...merging...thanks

**Pull request merged**
