### PR TITLE
Wiki refactor skyrocket

### PR DESCRIPTION
**Pull request by lordneeko**
I left the information in the development section and some of the common sections alone, since in general many of them will apply to the upcoming Skyviper models as well (APWeb, software loading, firmware resets, etc)  This is a first attempt at refactoring.  You may or may not like the format.  The intential was to build a Skyrocket main landing page, with subpages (expandable via the toctree) for skyviper models, starting with a subpage for the v2450 and have all v2450 pages under that branch.

I don't have the ability to build the site....I've tried and failed...so I haven't been able to test this.

### CODE REVIEW

**Comment by hamishwillee** [comment]
Hi @lordneeko 
Vagrant is the best way to go for testing this locally - as per http://ardupilot.org/dev/docs/common-wiki_editing_guide.html#building-testing-docs-locally

What problems have you had with this?

**Comment by lordneeko** [comment]
8 only have a Windows PC. Will it work in Linux for Windows?

**Comment by hamishwillee** [comment]
Vagrant runs on Windows - it basically sets up a separate environment inside windows for you to build the sources. After building both sources and final product are available for you from within Windows. The instructions are self-explanatory. The toolchain is free.

**Comment by lordneeko** [comment]
Ok, cool. Had no idea vagrant could work in windows I'll try it it next
time I have a chance

**Comment by lordneeko** [comment]
Ok so I found some issues by building it using Vagrant, but I'm having an issue, and maybe it is a limitation of the system.  I'm trying to nest a tree and I've done it according to the editing guide, but it just doesn't seem to be doing what I thought it should.  Please look at the attachment. I'm trying to nest the "More Info" section under the V2450 GPS section, but the collapsible section is not showing up. It correctly shows the links in the "More Info" section, but doesn't create the tree menu on the left. It does, in the skyrocket.rst file, correctly create the "SkyRocket Products with Ardupilot" and Skyviper V2450 GPS sections. Help?

sv_wiki

**Comment by hamishwillee** [comment]
I thing that you've reached the nesting limitation of the sidebar. You can continue to nest to a certain level, but after that the page TOC is no longer displayed. 
You'd have to test to work out how deep the pages and TOCs can go. My recollection is that this is theme dependent and is about 4 levels down. 

In any case, I don't  that you're doing anything wrong in the TOC declaration. 

Easiest test you could do is try put the current more info text into the parent page. If that builds sidebar TOC then you KNOW your text is correct and that you've hit sidebar limitation. 

Is the parent level "Skyrocket products with ArduPilot actually needed"? I would look at ways of moving the tree up one level, and given that you're inside an ardupilot wiki, that topic would look like a good one to lose.

**Comment by lordneeko** [comment]
Good points. I'll look into that

**Comment by lordneeko** [comment]
Ok Now I've got it working.  See if this is good for merge.  Here is a screenshot.

image

**Comment by lordneeko** [comment]
It says there are conflicts here...but I don't know how to fix. I compared them and didn't see any differences...
The new skyviper products are about to hit.

**Comment by khancyr** [comment]
Rebase and correct some style and typo.

**Comment by auturgy** [comment]
ping @tridge or @peterbarker to approve before merging.

**Comment by lordneeko** [comment]
Honestly, I'm not even sure I even like this refactor. At the time it seemed to make sense, but now I'm having a hard time trying to figure out why i did what i did.
I'm going to stare at it a bit more, but I think I'm going to close it, and perhaps start over. The updates to the main page to mention the new models is probably enough.

**Pull request closed without merging**
