### PR TITLE
Remove ampersand from EKF/DCM failsafe page's title

### PR DESCRIPTION
**Pull request by rmackay9**
Remove ampersand from EKF/DCM failsafe page

### CODE REVIEW

**Comment by rmackay9** [comment]
It's a bit weird how it makes lots of spacing changes.  I only wanted to change one character.  Should I worry about this?

**Comment by magicrub** [comment]
I hate that too

**Comment by jpkh** [comment]
Yeah some editors does that. Normally no need to worry, just looks ugly

**Comment by jpkh** [comment]
merged

**Pull request merged**
