### PR TITLE
Clarity to locations

### PR DESCRIPTION
**Pull request by magicrub**
Added Location file details

### CODE REVIEW

**Comment by tridge** [comment]
applied, thanks
feel free to push any doc changes directly btw

**Comment by magicrub** [comment]
Thanks tridge. I editied that entirely from my cell phone so I was going to
wait until some desktop eyes saw it :)

**Comment by hamishwillee** [comment]
I find it difficult to work out what the changes are :-(. Looks fine though.

**Comment by magicrub** [comment]
Yeah, the changes thing is silly. I change 1 line in the github editor and
it changes a ton of whitespace.

**Comment by WickedShell** [comment]
I honestly wish the editor could be disabled... It encourages direct
commits, gives a poor chance to review things, and can cause far more
commits then are desired. (More of a statement for the autopilot side then
the wiki side).

**Comment by magicrub** [comment]
But but but it let me commit straight from my cell phone! :) and that's
good i think. Right?

**Comment by hamishwillee** [comment]
@magicrub @WickedShell Updating in your phone is a good thing for careful users making minor changes. For bigger changes it's better to build and test the layout. 

I somewhat agree with @WickedShell but I'd rather make the editor behave correctly. I thought this might be fixed using a .gitattributes file: https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings but my [test case](https://github.com/ArduPilot/ardupilot_wiki/pull/426/files) shows that even with gitattributes set the editor still does the wrong thing. Am I missing something obvious?

**Pull request closed without merging**
