### PR TITLE
Correct case statement examples

### PR DESCRIPTION
**Pull request by jaxxzer**

### CODE REVIEW

**Comment by magicrub** [comment]
@lucasdemarchi you made the original style, please take a look at this. You too @rmackay9 and @tridge

**Comment by OXINARF** [comment]
This is wrong, the sentence is what needs to be changed. This was changed recently with a vote in the dev call.

**Comment by WickedShell** [comment]
Didn't we vote to change the style on the dev call? Or have I just forgotten what the outcome of that was?

**Comment by rmackay9** [comment]
Yes, we changed the style guide a couple of weeks ago on the dev call and then I updated the wiki:
http://ardupilot.org/dev/docs/style-guide.html

So, I'll close this if that's ok..Sorry @jaxxzer!

**Comment by magicrub** [comment]
Doh! I updated the wiki on the switch statement during the call but I think I forgot to save and push my changes!

**Pull request closed without merging**
