### PR TITLE
Update to using the install-prereqs-ubuntu.sh

### PR DESCRIPTION
**Pull request by dyyap**
added to change permissions use chmod

### CODE REVIEW

**Comment by magicrub** [comment]
why would you not have access to a repo you just checked out? Can you describe the scenario?

**Comment by dyyap** [comment]
I used windows 10 WSL and followed tre instructions up to the point of using the script however it only had read and one write privilege no executable

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by peterbarker** [comment]
Sorry, this is the incorrect fix.  The scripts should be executable, but we lost that when they were moved, sadly.  Do you feel like doing a PR against master making these scripts in the environment_install directory executable?

What would be welcome is a patch to correct the path to the script here - it's correct in one spot but wrong in another...

@stephendade for visibility

**Comment by dyyap** [comment]
I thought that maybe some of the scripts were meant for internal use in some other scripts, when I just changed permissions for one script I did not know if the other scripts wanted executable permission as well. Other than that permission the other steps work fine.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by peterbarker** [comment]
On Sun, 21 Apr 2019, dyyap wrote:

> I thought that maybe some of the scripts were meant for internal use in some other scripts, when I just changed permissions for one script I did not know
> if the other scripts wanted executable permission as well. Other than that permission the other steps work fine.

Uh... so is that a yes or no to PRing a set of chmod+x'd scripts? :-)


Peter

**Comment by dyyap** [comment]
Yes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephendade** [comment]
FYI, the scripts have been updated in ardupilot to have the executable permission.

**Comment by tridge** [comment]
thanks, I fixed the conflict and added your chmod update

**Pull request closed without merging**
