### PR TITLE
common-rssi-received-signal-strength-indication: rework page

### PR DESCRIPTION
**Pull request by vierfuffzig**
#1342 

i consider this WIP as for now and would appreciate comments / corrections

### CODE REVIEW

**Comment by Hwurzburg** [comment]
Basti, you might want to add a comment that some flight controllers (like OmnibusF4Pro) only are rated for 0-3.3V on their analog RSSI input pins. If the RX provides 0-5V, then a 2:1 resistive divider might be required between the RX and FC. However, most modern RXs output 0-3.3V. Check individual board/receiver specifications if in doubt.
Probably more important for analog airspeed sensors using analog inputs, however. I will put an update to that section on my own list of to-dos.

**Comment by vierfuffzig** [comment]
thanks henry, will do.
beyond that i‘d appreciate guidance on RSSI_TYPE 3 (receiver protocol, SUMD / ST24). i’m having a hard time figuring out if this has been successfully tested on ChibiOS, i don‘t have hardware at hand to do tests myself.

**Comment by vierfuffzig** [comment]
updated accordingly, added description for RSSI_TYPE = 3 (receiver protocol), assuming it works as supposed regarding recent additions to AP_HAL/RCInput.h. ready to review / merge.

**Comment by rmackay9** [comment]
Merged, thanks.

**Pull request merged**
