### PR TITLE
Update: fixed broken link

### PR DESCRIPTION
**Pull request by adalta87**
@Hwurzburg  
again the dronkit python link was broke so I updated it to the dronkit webpage. also 3dr links broken and I removed the link completely as they will never be back. not sure if you want the dronekit link to go to their webpage or the dronekit github?

### CODE REVIEW

**Comment by Hwurzburg** [comment]
this has nothing to do with your comment...use this for cuav resellers https://www.cuav.net/en/resellers/

**Comment by Hwurzburg** [comment]
are you on discord?,we need to chat

**Comment by adalta87** [comment]
sorry had to many windows open

**Comment by Hwurzburg** [comment]
no problem  stiil need to chat about how to proceed...using the web based editor is non optimum....makes it hard to squash multiple commits...you need to set up an editing environment...I can help

**Comment by adalta87** [comment]
copy will stop editing

**Comment by Hwurzburg** [comment]
really welcome the help! need to make it less time consuming for both of us...am on holiday this week, but when I return, ping me on discord and we can chat

**Comment by adalta87** [comment]
@Hwurzburg 

will look into these for editing https://ardupilot.org/copter/docs/common-wiki-editing-setup.html
sorry to make a lot of work.

**Comment by Hwurzburg** [comment]
squashed, merging...when you need help on the wiki editing environment we can share screen on Discord and I can help you or walk you thru submitting a change

**Pull request merged**
