### PR TITLE
Add Copter and Rover records pages

### PR DESCRIPTION
**Pull request by peterbarker**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
these need to be linked somewhere (I suggest in the Appendix) and have TOClist entries....this is a build error wiki CI does not flag!

**Comment by peterbarker** [comment]
> these need to be linked somewhere (I suggest in the Appendix) and have TOClist entries....this is a build error wiki CI does not flag!

Yep, I do realise these are unlinked - just looking for guidance on that...

**Comment by Hwurzburg** [comment]
I suggest adding a Records topic here https://ardupilot.org/copter/docs/common-appendix.html... have plane,copter,and rover links to those pages on it under a toclist header killing two birds with one stone

**Comment by peterbarker** [comment]
> I suggest adding a Records topic here https://ardupilot.org/copter/docs/common-appendix.html... have plane,copter,and rover links to those pages on it under a toclist header killing two birds with one stone

I've added it to the toctree for each of Rover, Plane and Copter.

I haven't put it into the appendix - doesn't look like we have precedent for vehicle-specific stuff in there.

**Comment by Hwurzburg** [comment]
@peterbarker I really want to keep only required info in left menus, so to avoid list-creep I moved the records info to the appendix
unless you object, I will merge tomorrow after CI and you get a chance to look tonight

**Pull request merged**
