### PR TITLE
Including The Cube

### PR DESCRIPTION
**Pull request by ThisIsTheOnlyUsernameAvailable**

### CODE REVIEW

**Comment by auturgy** [comment]
Can you make all these changes in a branch, then pr the branch, rather than these single commits?

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Happy to, but this is my first contribution on GitHub.  I followed Tridge's instructions on the Dev site.

How do I consolidate?

**Comment by proficnc** [comment]
Managing git is a lot to ask for wiki management...

These are simple changes, and it’s possible that non fit users are doing this

**Comment by auturgy** [comment]
It’s ok: and much appreciated.
I’m guessing you’re doing this from a browser, which is fine. We can go through each pr and merge etc - so don’t stop!

The other way, also in the wiki, is to fork and clone the wiki, create a new branch, then make your changes in that new branch on a local machine and push it up all at once. If you’re keen to help out with the wiki, we can set up a time to walk through that on gitter perhaps?

Regards,

James

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Thanks James.  

I am keen to contribute to the project but don't have development skills.  I can, however, contribute to the Wiki.  

I'll try the fork/clone/branch method described on the dev wiki.  It looks well documented so I'll give it a crack for my next round of edits.

**Comment by auturgy** [comment]
Cool, thanks!

Regards,

James

**Comment by magicrub** [comment]
Please keep in mind that a thing called a pixhawk still exists so we can not remove it from the whole wiki. Just references to the 2.1

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
@magicrub noted.  The edits thus far have either been to replace PH2, PH2.1 or to clarify the platform differentiation from the Pixhawk board.  EG:

* "Pixhawk, APM or Pixhawk2" -> "Pixhawk, APM or Cube"
* "Pixhawk or APM" -> "Pixhawk, APM or Cube"
* "Mount your Pixhawk in your copter" -> "Mount your flight controller in your copter".

**Comment by auturgy** [comment]
Thanks!  I made a couple of little changes (this one didn't need to list all the FC types, so I changed to just Flight Controller).

**Pull request merged**
