### PR TITLE
common-cameras-and-gimbals.rst: remove dead link

### PR DESCRIPTION
**Pull request by vierfuffzig**
tarot website down, linked hardware item outdated

### CODE REVIEW

**Comment by auturgy** [comment]
Thanks

**Comment by vierfuffzig** [comment]
thanks @auturgy , maybe #1420 can be closed now?

**Comment by rmackay9** [comment]
hold on.. did we just remove the tarot gimbal page?  The tarot gimbal is pretty commonly used I think.

**Comment by rmackay9** [comment]
I've restored the Tarot 2D gimbal.  This is actually the 2nd time I've had to do this so let's not delete it a 3rd time ok? :-)

**Comment by auturgy** [comment]
It’s a dead link.
 that gimbal was relevant in 2013, but isn’t available in 2019. Better that it’s retired.

Regards,

James

**Comment by rmackay9** [comment]
If someone wants to upgrade the page to the more recent versions of the Tarot gimbals then that's great but I think the page still has some value.

**Comment by auturgy** [comment]
This page exists because 3DR used to sell them. It was never a gimbal we should actually have been recommending over others. I don’t think we should update it: I really think this page should go.

**Comment by rmackay9** [comment]
@auturgy, I'm afraid I can't agree.. There are no other Ready-to-use brushless gimbals on our camera/gimbals wiki page.  Removing the one example that we have, whether it's perhaps more difficult to find than it once was or not isn't a great idea I think.

**Comment by vierfuffzig** [comment]
@rmackay9 would you agree to have the site point out that this is an illustrative sample and have the dead links and references removed or replaced by local backup copies wherever possible?

**Comment by rmackay9** [comment]
@vierfuffzig, sure, that sounds good.

**Pull request merged**
