### PR TITLE
A tool to help to deal with broken links

### PR DESCRIPTION
**Pull request by brunoolivieri**
It can parse the RST files or built HTML files. It is not fast enough to insert in the build script, but help me to find some broken link that I already did a couple of PRs to fix, and I inserted some of them in the issue #982

I guess this is a script like something used in #1382.

Due to some isses[1], it presents lots of false positives. I tried to bypass this [2], but some help would be appreciated regarding web servers responses.

- When using the parser for RST files, it is faster than HTML because it looks less* files and is not able to find any link**.   (* IFF "common" folder is not copied across vehicles yet.)(** Only look for sphinx expected links.)

- When using the parser for HTML, it has a more comprehensive parser for HTML "a" attributes.

[1] https://stackoverflow.com/questions/47506092/python-requests-get-always-get-404
[2] https://stackoverflow.com/questions/27652543/how-to-use-python-requests-to-fake-a-browser-visit

### CODE REVIEW

**Comment by khancyr** [comment]
Haa what a pain... I am sorry for you ...but Sphinx is able to do it at build time...

**Comment by peterbarker** [comment]
@khancyr how does one get Sphinx to do that?

Are there advantages to doing it externally?  Cases Sphinx doesn't handle?

**Comment by hamishwillee** [comment]
I think it's just `make linkcheck` or  ` sphinx-build -b linkcheck`. It runs a check on every URL. You will need to do it on every wiki.

This is what I used to do occasionally and then copy the broken links into issues for tracking.

**Comment by brunoolivieri** [comment]
@khancyr yes! An unnecessary pain... I should spend time back in parameters versioning. LOL!  But I read in some place that sphinx could not do that. My bad.

@hamishwillee thanks!

@peterbarker and all: Now, I can not see a significant advantage in inserting my script. Looks redundant...  I also like @Hwurzburg idea of the use of an offsite tool (deadlinkchecker.com)

May be to build the wiki locally once a while using the link checkers would be enough to look for deadlinks.

Should I close it?

**Comment by brunoolivieri** [comment]
During the wiki call today we chose close it.

**Pull request closed without merging**
