### PR TITLE
Sonar JSN-SR04T

### PR DESCRIPTION
**Pull request by AlksSAV**
Support for the new JSN-SR04T device
https://discuss.ardupilot.org/t/sonar-jsn-sr04t/77789

### CODE REVIEW

**Comment by Hwurzburg** [comment]
remove gitignore change and do in another PR (but not sure if its really valid)....need to add this to the TOC list on the rangefinder landing page....should be a single commit..thanks

**Comment by AlksSAV** [comment]
> remove gitignore change

- Removed gitignore changes
- add to list JSN-SR04T

**Comment by Hwurzburg** [comment]
sorry, tried to push a few corrections and a squash of the commits into a single one....unfortunately did not notice that  this was not a branch, but your main, so I pushed a current main to yours...fear not I have the changes and will PR with you as co-author for your credit...and merge...
next time create a working branch off your master and PR it to the wiki...that way we can make changes and push back into your PR...

**Comment by AlksSAV** [comment]
> sorry, tried to push a few corrections and a squash of the commits into a single one....unfortunately did not notice that this was not a branch, but your main, so I pushed a current main to yours...fear not I have the changes and will PR (#3877) with you as co-author for your credit...and merge... next time create a working branch off your master and PR it to the wiki...that way we can make changes and push back into your PR...

Excellent. Next time I'll do it properly.

**Pull request closed without merging**
