### PR TITLE
Fix broken links in FrSky Telemetry

### PR DESCRIPTION
**Pull request by Naterater**
One link wasn't going external. The other was a 404 error due to a change.

### CODE REVIEW

**Comment by auturgy** [comment]
Thanks Nate,
Before this is merged, can you check the other links on that page?
Might as well hit them all at once.

Regards,

James

**Comment by Naterater** [comment]
Yeah,

It looks like all of the FrSky links changed. I'll see what I can find and try to amend the PR.

**Comment by auturgy** [comment]
Thanks 

Regards,

James

**Comment by hamishwillee** [comment]
FYI, current link errors in this doc on master are:

(line   49) redirect  https://www.gitbook.com/book/opentx/opentx-taranis-manual/details - with Found to https://legacy.gitbook.com/book/opentx/opentx-taranis-manual/details
(line   49) redirect  https://www.gitbook.com/book/opentx/opentx-taranis-manual/details - with Found to https://legacy.gitbook.com/book/opentx/opentx-taranis-manual/details
(line   84) broken    http://open-txu.org/2-6-02-frsky-variometer-sensor-andrew-newton-02272015-2/ - HTTP Error 404: Not Found

**Comment by Hwurzburg** [comment]
Nate, could you check and update the PR for the broken links hamishwillee found also?I will then recommend a merge...thanks!

**Comment by Hwurzburg** [comment]
I am merging this...I will review after and fix any other broken links

**Pull request merged**
