### PR TITLE
Add note about including libc6-i386 for px4 on 64 bit linux

### PR DESCRIPTION
**Pull request by kwikius**
See  https://github.com/ArduPilot/ardupilot/issues/3999

### CODE REVIEW

**Comment by hamishwillee** [comment]
@kwikius I don't remember installing this on Ubuntu 14.04 - what 64bit linux platform are you using? Can you add full stop at the end of your sentence?
Thanks!

**Comment by kwikius** [comment]
@hamishwillee 
I dont have a 64 bit Linux system to test on, but if you read the issue referenced, which gave cryptic output, the fix was to install the relevant 32 bit libraries. I remember having to do this for a Travis build. Missing libraries are tricky since for the majority that have them installed everything works fine
However I am happy to see if anyone with more experience would like to comment

**Comment by kwikius** [comment]
I have just confirmed that this library is required now and missing on a new install of 64 bit Ubuntu at least, since I recently did a fresh install of 64 bit Ubuntu. 
On entering the bin directory for arm-none-eabi-gcc/bin and executing 
~> ./arm-none-eabi-gcc --version
returns
~> bash: ./arm-none-eabi-gcc: No such file or directory
Now install libc6-i386 by Do 
~> sudo apt-get install libc6-i386
And the above  command then works as expected.I guess that on 64 bit Ubuntu the 32 bit gcc app isnt recognised as an app until said lib is installed.

**Comment by ryanglennreed** [comment]
Z

**Comment by hamishwillee** [comment]
@magicrub This sounds reasonable enough https://github.com/ArduPilot/ardupilot_wiki/pull/435/files?w=1 . Are you OK to merge?

**Comment by magicrub** [comment]
I like how you added the ?w=1 because it's a huge mess without it! :)

No objection from me, simple addition. I haven't tested the new windows changes that everyone is talking about but I imagine I will be forced to soon.

**Comment by hamishwillee** [comment]
I haven't tested either. Working hard getting ready for another project.

**Pull request merged**
