### PR TITLE
frontend: use lazyloading for images

### PR DESCRIPTION
**Pull request by khancyr**
This allow the browser to load images only on need.
This doesn't work on Safari for now

### CODE REVIEW

**Comment by brunoolivieri** [comment]
What happens in Safari?  

The page loads ok in Safari?

**Comment by khancyr** [comment]
According to https://caniuse.com/loading-lazy-attr lazy loading isn't supported

**Comment by Hwurzburg** [comment]
@brunoolivieri can you approve so it can be merged?

**Comment by brunoolivieri** [comment]
LGTM

**Pull request merged**
