### PR TITLE
Add CUAV Neo v2 pro (UAVCAN GPS)

### PR DESCRIPTION
**Pull request by cuhome**
NEO V2 pro is UAVCAN GPS developed by CUAV, which has been supported in ardupilot 4.0 firmware.

### CODE REVIEW

**Comment by cuhome** [comment]
@Hwurzburg Can you check it?

**Comment by Hwurzburg** [comment]
Hongle, just pushed a commit which updates and edits and squashes all your commits into one for housekeeping....if it looks good to you, I will merge it....thanks

**Comment by cuhome** [comment]
@Hwurzburg Great. Do I need to close this pr?

**Comment by Hwurzburg** [comment]
No...I will merge it now

**Pull request merged**
