### PR TITLE
Solo Remastered wiki pages

### PR DESCRIPTION
**Pull request by Pedals2Paddles**
This is my first stab at creating some new wiki pages for ArduPilot. These pages are for upgrading the 3DR Solo to ArduCopter 3.5 with a Pixhawk 2.1.  There is a landing page, instructions using Solex, and instructions using Mission Planner and WinSCP.  There are a bunch of images too.

I created and edited these in Notepad++.  I am unable to use the RST rendering tool on Windows to test it though.  So I used some online tools to render the pages and it gets me close.  Absent the ability to really test render the right way, I'm hoping to put these up on the server so I can see how they're coming out.  And obviously not link to them in the common pages or navbars until it's really polished up and done.

### CODE REVIEW

**Comment by hamishwillee** [comment]
>  Absent the ability to really test render the right way, I'm hoping to put these up on the server so I can see how they're coming out. And obviously not link to them in the common pages or navbars until it's really polished up and done.

You have the ability -see [here](http://ardupilot.org/copter/docs/common-wiki_editing_guide.html#building-testing-docs-locally).

**Comment by Pedals2Paddles** [comment]
I uninstalled everything and reinstalled everything. It worked finally! This drove me nuts all evening. I have a few things to clean up that I will be working on this morning. It came out pretty decent though.  I will update this later today.

**Comment by Pedals2Paddles** [comment]
So much for some "quick fixes".  This turned into an all day project. But I believe I have it in good shape now.  Can our Wiki masters here take a look?

**Comment by rmackay9** [comment]
I think we should make it a top-line category in the menu.  So maybe right around "TriCopter".  It's probably done by updating this file:

https://github.com/ArduPilot/ardupilot_wiki/blob/master/copter/source/index.rst

**Comment by hamishwillee** [comment]
> . It's probably done by updating this file: https://github.com/ArduPilot/ardupilot_wiki/blob/master/copter/source/index.rst

Yes, that's the right way to do it. The bit in toctree at the bottom of the page.

**Pull request merged**
