### PR TITLE
Update building-setup-linux.rst

### PR DESCRIPTION
**Pull request by auturgy**
NuttX and make are no longer used by ArduPilot

### CODE REVIEW

**Comment by khancyr** [comment]
Waf distclean instead of rm -rf no?

**Comment by peterbarker** [comment]
@khancyr nuke the site from orbit; it's the only way to be sure.

**Comment by khancyr** [comment]
?
Waf distclean does the same things than rm -rf but also clean waf stuff.
Why do you consider it as nuke ? ( git clean -d -x -f)

**Comment by Hwurzburg** [comment]
approvals in ...merging

**Pull request merged**
