### PR TITLE
Lua scripts: Add note on situation for F4 autopilots

### PR DESCRIPTION
**Pull request by olliw42**
Small text addition to avoid that imprudent users like me run into issues like that https://github.com/ArduPilot/ardupilot/issues/15683 :)

F4's are still widely around, IMHO.

### CODE REVIEW

**Comment by auturgy** [comment]
Thanks Olli, appreciated

**Comment by Hwurzburg** [comment]
which F4 autopilot that ArudPilot supports has 2MB of flash?

**Comment by kd0aij** [comment]
(base) 11:19:05 (master) ~/linux_git/kd0aij/ardupilot/libraries/AP_HAL_ChibiOS/hwdef$ find . -name "hwdef.dat" -exec grep -H -B 20 "FLASH_SIZE_KB 2048" {} \;  | grep STM32F4

./Pixracer/hwdef.dat-MCU STM32F4xx STM32F427xx
./QioTekZealotF427/hwdef.dat-MCU STM32F4xx STM32F427xx
./VRBrain-v54/hwdef.dat-MCU STM32F4xx STM32F427xx
./DrotekP3Pro/hwdef.dat-MCU STM32F4xx STM32F469xx
./mindpx-v2/hwdef.dat-MCU STM32F4xx STM32F427xx
./luminousbee4/hwdef.dat-MCU STM32F4xx STM32F427xx

**Comment by Hwurzburg** [comment]
thanks....just wanted to be sure none were listed in the firmware limitations page....
probably should add the other RAM impactors from that page....ie batch sampling and large log buffers...will put on my list

**Pull request merged**
