### PR TITLE
added a page on Vicon setup for copters

### PR DESCRIPTION
**Pull request by tridge**

### CODE REVIEW

**Comment by rmackay9** [comment]
I think this should be put under common-optional-hardware and renamed to "Vicon for Non-GPS navigation" to fit in with similar pages like "OptiTrack for Non-GPS navigation".  It's possible that we have enough of these that we should group all these pages under a single "Non-GPS navigation" landing page.

- Marvelmind for Non-GPS Navigation
- Pozyx for Non-GPS navigation
- OptiTrack for Non-GPS navigation
- VIO tracking camera for Non-GPS navigation
- ZED for Non-GPS navigation

**Comment by brunoolivieri** [comment]
If you prefer,  you may merge this PR itself, and I can rearrange the files in a new landing page.

**Comment by rmackay9** [comment]
@brunoolivieri, that would be good thanks!

**Comment by Hwurzburg** [comment]
@brunoolivieri merging....thanks for volunteering to fix this after the merge....

**Comment by brunoolivieri** [comment]
PR #2001  tries to covers that.

**Pull request merged**
