### PR TITLE
Fixed the link to Zubax documentation website

### PR DESCRIPTION
**Pull request by pavel-kirienko**

### CODE REVIEW

**Comment by OXINARF** [comment]
Any reason not to use the long link? If the link ever changes and we don't update it here, it is easier to track down the new link if we have a long link instead of a short link.

**Comment by magicrub** [comment]
@OXINARF  I imagine it's so he can maintain the forwarding on his end instead of updating us on each change. Pros/cons both ways. Merging this as-is, we can discuss changing it later if you're really passionate about it

**Comment by OXINARF** [comment]
@magicrub The short link is quite likely done by the Confluence system they are using and if they ever change it, it is probable they aren't going to keep the short link. I'm not sure what the rush to merge was, but OK.

**Comment by pavel-kirienko** [comment]
Folks, the short link allows us to keep external references unchanged even
if the linked article gets renamed.

On Jul 18, 2017 11:25 PM, "Francisco Ferreira" <notifications@github.com>
wrote:

@magicrub <https://github.com/magicrub> The short link is quite likely done
by the Confluence system they are using and if they ever change it, it is
probable they aren't going to keep the short link. I'm not sure what the
rush to merge was, but OK.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArduPilot/ardupilot_wiki/pull/884#issuecomment-316186738>,
or mute the thread

**Pull request merged**
