### PR TITLE
Update common-stores.rst

### PR DESCRIPTION
**Pull request by auturgy**
removed 3DR and bracketed comment from Craft&Theory.

### CODE REVIEW

**Comment by auturgy** [comment]
I fully agree with supporting partners, but short descriptions like yours only work for a subset.
We need to treat all partners equally. An alternate approach might be to split the list into labelled groups. It’s an open discussion topic, hopefully we’ll get some clarity and direction in the very near future.

**Comment by CraigElder** [comment]
@auturgy Being listed on this page is not exclusive to partners and having detail about what Craft & Theory sell does not give them an unfair advantage but removing the detail deprives our users of useful detail.

**Comment by rmackay9** [comment]
@CraigElder, actually we made a decision recently that we would only add partners to the stores page going forward.  We're grandfathering in existing stores (i.e. non-partners can stay if they're already on the page).

Perhaps that decision will be viewed unfavourably by some but I hope not.  The thinking is that stores are for-profit entities and we hope the decision will encourage some more companies profit based on ardupilot will in turn support ardupilot a bit financially (the donation to become a partner is very reasonable).

**Comment by CraigElder** [comment]
@rmackay9 Sorry I don't remember that vote

**Comment by OXINARF** [comment]
@rmackay9 I'm in the same situation as @CraigElder, I don't know where that decision was made. I know this page was discussed in a dev call I wasn't in, but from reading the minutes and asking a member that was there, I didn't get any feedback that rule was approved.

**Pull request closed without merging**
