### PR TITLE
common: add makeflyeasy PixSurveyA1

### PR DESCRIPTION
**Pull request by mfe-xiao**

### CODE REVIEW

**Comment by Hwurzburg** [comment]
thanks....will do a little touch up and add once the code PR is merged....can you supply a higher resolution photo of the board so that the output numbering can be read when zoomed in? thanks

**Review by Hwurzburg — CHANGES_REQUESTED** [review]
needs higher res photo of device

**Comment by Hwurzburg** [comment]
Thanks....one more thing....which F4 processor is used?

**Comment by mfe-xiao** [comment]
> Thanks....one more thing....which F4 processor is used?

It's STM32F427VIT6.

**Comment by Hwurzburg** [comment]
@mfe-xiao Thanks...I made the modifications needed and was ready to push it back to this PR. However, that is not  possible since you made them to your master branch and submitted this PR from that branch...
At this point, I can create a new PR with those modifications and you as Co-author and submit it for your review and then merge it, and close this one, if that is okay....

**Comment by mfe-xiao** [comment]
> @mfe-xiao Thanks...I made the modifications needed and was ready to push it back to this PR. However, that is not possible since you made them to your master branch and submitted this PR from that branch... At this point, I can create a new PR with those modifications and you as Co-author and submit it for your review and then merge it, and close this one, if that is okay....

okay,thank you very much.

**Comment by Hwurzburg** [comment]
okay please review https://github.com/ArduPilot/ardupilot_wiki/pull/4467   if okay I will merge and close this one...thanks

**Comment by mfe-xiao** [comment]
> okay please review #4467 if okay I will merge and close this one...thanks

it's okay.

**Pull request closed without merging**
