### PR TITLE
Update Repurposed FrSky telemetry page

### PR DESCRIPTION
**Pull request by tomlauzon**
Includes Scripts and conflict warning.

### CODE REVIEW

**Comment by tomlauzon** [comment]
No, but there is a link to rc groups: https://www.rcgroups.com/forums/showpost.php?p=37213943&postcount=48

**Comment by OXINARF** [comment]
It's the same person, so it's preferable to link to our forum instead.

The only thing I don't like about this PR is the images coming from an external GitHub repo, it opens up the possibility of inappropriate images showing up in our wiki.

**Comment by tomlauzon** [comment]
@auturgy the executable in question is a text lua script, so it is source code as well. Also linking to something is not distributing it. But that's beside the point. The question was whether we should host the screenshots on the wiki to prevent the pictures from being replaced at the source and showing them on the wiki. I can do it when I have a second. It takes a bit more work, and it's a good idea to let the author know that we intend to host the screenshots if that's what we want to do.

**Comment by auturgy** [comment]
Fair point re Lua (being interpretted etc).  My bad.  "linking to something" vs "distributing" is a nuanced discussion, but accepting the point that for lua the executable is the source, it isn't really relevant for here.
More importantly, the download link on the ardupilot forum didn't work, so we either need to host the LuaPlane script ourselves, link to rcg, or put it somewhere else.  It's also a few merges behind LuaPilot, so may have some minor issues with OpenTX >2.1 (I can't test, as my Taranis is 6000 miles away).  Can someone confirm which OpenTX versions the linked LuaPlane (fully) works with?

**Comment by Hwurzburg** [comment]
Tom, I am trying to clean up the wiki PRs, here....if you could drop the images, but leave the LUA script links (checked as valid by me), I would recommend merging this....thanks

**Pull request closed without merging**
